// Builtin reference: names, signatures, and one-line docs for every builtin
// in luxel-core's VM table (crates/luxel-core/src/vm.rs BUILTINS — keep in
// sync). Drives editor autocomplete today and the language docs; values are
// 16.16 fixed point unless noted.

export interface BuiltinDoc {
  name: string;
  sig: string;
  doc: string;
}

export const BUILTINS: BuiltinDoc[] = [
  // math
  { name: "abs", sig: "abs(x)", doc: "Absolute value." },
  { name: "floor", sig: "floor(x)", doc: "Round down to the nearest integer." },
  { name: "ceil", sig: "ceil(x)", doc: "Round up to the nearest integer." },
  { name: "round", sig: "round(x)", doc: "Round to nearest: floor(x + 0.5)." },
  { name: "trunc", sig: "trunc(x)", doc: "Drop the fractional part (toward zero)." },
  { name: "frac", sig: "frac(x)", doc: "Fractional part of x." },
  { name: "clamp", sig: "clamp(x, low, high)", doc: "Constrain x into [low, high]." },
  { name: "min", sig: "min(a, b)", doc: "Smaller of two values." },
  { name: "max", sig: "max(a, b)", doc: "Larger of two values." },
  { name: "mod", sig: "mod(x, y)", doc: "Floored modulo — result has y's sign (unlike %)." },
  { name: "sqrt", sig: "sqrt(x)", doc: "Square root; sign-preserving (sqrt(-4) = -2)." },
  { name: "sin", sig: "sin(radians)", doc: "Sine." },
  { name: "cos", sig: "cos(radians)", doc: "Cosine." },
  { name: "tan", sig: "tan(radians)", doc: "Tangent." },
  { name: "asin", sig: "asin(x)", doc: "Arc sine, radians." },
  { name: "acos", sig: "acos(x)", doc: "Arc cosine, radians." },
  { name: "atan", sig: "atan(x)", doc: "Arc tangent, radians." },
  { name: "atan2", sig: "atan2(y, x)", doc: "Angle of (x, y) from the +x axis, radians." },
  { name: "pow", sig: "pow(base, exp)", doc: "base raised to exp." },
  { name: "exp", sig: "exp(x)", doc: "e^x." },
  { name: "log", sig: "log(x)", doc: "Natural logarithm." },
  { name: "log2", sig: "log2(x)", doc: "Base-2 logarithm." },
  { name: "hypot", sig: "hypot(a, b)", doc: "sqrt(a² + b²)." },
  { name: "hypot3", sig: "hypot3(a, b, c)", doc: "sqrt(a² + b² + c²)." },
  // Luxel extension builtins (not in Pixel Blaze)
  { name: "map", sig: "map(x, inLo, inHi, outLo, outHi)", doc: "Re-range x from one interval to another. (Luxel)" },
  { name: "fract", sig: "fract(x)", doc: "Fractional part of x (alias of frac). (Luxel)" },
  { name: "lerp", sig: "lerp(a, b, t)", doc: "Linear blend of a and b by t (alias of mix). (Luxel)" },
  { name: "length", sig: "length(a, b)", doc: "Vector length sqrt(a² + b²) (alias of hypot). (Luxel)" },
  { name: "length3", sig: "length3(a, b, c)", doc: "3D vector length (alias of hypot3). (Luxel)" },
  { name: "sign", sig: "sign(x)", doc: "-1, 0, or 1 by the sign of x. (Luxel)" },
  { name: "step", sig: "step(edge, x)", doc: "0 if x < edge, else 1. (Luxel)" },
  { name: "saturate", sig: "saturate(x)", doc: "Clamp x to 0..1. (Luxel)" },
  { name: "dist", sig: "dist(x1, y1, x2, y2)", doc: "Distance between two 2D points. (Luxel)" },
  { name: "dist3", sig: "dist3(x1,y1,z1, x2,y2,z2)", doc: "Distance between two 3D points. (Luxel)" },
  { name: "easeInQuad", sig: "easeInQuad(t)", doc: "Quadratic ease-in on 0..1. (Luxel)" },
  { name: "easeOutQuad", sig: "easeOutQuad(t)", doc: "Quadratic ease-out on 0..1. (Luxel)" },
  { name: "easeInOutQuad", sig: "easeInOutQuad(t)", doc: "Quadratic ease-in-out on 0..1. (Luxel)" },
  { name: "easeInCubic", sig: "easeInCubic(t)", doc: "Cubic ease-in on 0..1. (Luxel)" },
  { name: "easeOutCubic", sig: "easeOutCubic(t)", doc: "Cubic ease-out on 0..1. (Luxel)" },
  { name: "easeInOutCubic", sig: "easeInOutCubic(t)", doc: "Cubic ease-in-out on 0..1. (Luxel)" },
  { name: "easeOutBack", sig: "easeOutBack(t)", doc: "Ease-out that overshoots ~10% past 1 and settles back. (Luxel)" },
  { name: "easeOutElastic", sig: "easeOutElastic(t)", doc: "Ease-out with a decaying spring wobble around 1. (Luxel)" },
  { name: "easeOutBounce", sig: "easeOutBounce(t)", doc: "Ease-out that bounces like a dropped ball settling at 1. (Luxel)" },
  { name: "easeInSine", sig: "easeInSine(t)", doc: "Sinusoidal ease-in on 0..1. (Luxel)" },
  { name: "easeOutSine", sig: "easeOutSine(t)", doc: "Sinusoidal ease-out on 0..1. (Luxel)" },
  { name: "easeInOutSine", sig: "easeInOutSine(t)", doc: "Sinusoidal ease-in-out on 0..1. (Luxel)" },
  { name: "easeInQuart", sig: "easeInQuart(t)", doc: "Quartic ease-in on 0..1. (Luxel)" },
  { name: "easeOutQuart", sig: "easeOutQuart(t)", doc: "Quartic ease-out on 0..1. (Luxel)" },
  { name: "easeInOutQuart", sig: "easeInOutQuart(t)", doc: "Quartic ease-in-out on 0..1. (Luxel)" },
  { name: "easeInQuint", sig: "easeInQuint(t)", doc: "Quintic ease-in on 0..1. (Luxel)" },
  { name: "easeOutQuint", sig: "easeOutQuint(t)", doc: "Quintic ease-out on 0..1. (Luxel)" },
  { name: "easeInOutQuint", sig: "easeInOutQuint(t)", doc: "Quintic ease-in-out on 0..1. (Luxel)" },
  { name: "easeInExpo", sig: "easeInExpo(t)", doc: "Exponential ease-in on 0..1; exactly 0 at t=0. (Luxel)" },
  { name: "easeOutExpo", sig: "easeOutExpo(t)", doc: "Exponential ease-out on 0..1; exactly 1 at t=1. (Luxel)" },
  { name: "easeInOutExpo", sig: "easeInOutExpo(t)", doc: "Exponential ease-in-out on 0..1; endpoints pinned. (Luxel)" },
  { name: "easeInCirc", sig: "easeInCirc(t)", doc: "Circular ease-in on 0..1. (Luxel)" },
  { name: "easeOutCirc", sig: "easeOutCirc(t)", doc: "Circular ease-out on 0..1. (Luxel)" },
  { name: "easeInOutCirc", sig: "easeInOutCirc(t)", doc: "Circular ease-in-out on 0..1. (Luxel)" },
  { name: "easeInBack", sig: "easeInBack(t)", doc: "Ease-in that dips ~10% below 0 before accelerating. (Luxel)" },
  { name: "easeInOutBack", sig: "easeInOutBack(t)", doc: "Ease-in-out overshooting below 0 and past 1 at both ends. (Luxel)" },
  { name: "easeInElastic", sig: "easeInElastic(t)", doc: "Ease-in with a growing spring wobble around 0. (Luxel)" },
  { name: "easeInOutElastic", sig: "easeInOutElastic(t)", doc: "Ease-in-out with spring wobble at both ends. (Luxel)" },
  { name: "easeInBounce", sig: "easeInBounce(t)", doc: "Ease-in that bounces off 0 before rising (mirror of easeOutBounce). (Luxel)" },
  { name: "easeInOutBounce", sig: "easeInOutBounce(t)", doc: "Ease-in-out bouncing at both ends. (Luxel)" },
  { name: "beat", sig: "beat(bpm)", doc: "Sawtooth beat phase 0..1 at bpm on the engine clock. (Luxel)" },
  { name: "beatSin", sig: "beatSin(bpm, lo = 0, hi = 1)", doc: "Sine oscillation between lo and hi at bpm. (Luxel)" },
  { name: "hash", sig: "hash(x)", doc: "Deterministic 0..1 from x — stable per-pixel randomness (same input, same output, every frame and device). (Luxel)" },
  { name: "hash2", sig: "hash2(x, y)", doc: "Deterministic 0..1 from two inputs. (Luxel)" },
  { name: "blur1D", sig: "blur1D(arr, radius)", doc: "In-place box blur over arr (window 2·radius+1, edges clamped); returns arr. (Luxel)" },
  { name: "blur2D", sig: "blur2D(arr, w, h, radius)", doc: "In-place separable box blur over a row-major w×h canvas (edges clamped); returns arr. The diffusion loop of buffer-based 2D patterns as one call. (Luxel)" },
  { name: "feedback", sig: "feedback(arr, decay)", doc: "Multiply every element by decay in place (trails/glow); returns arr. (Luxel)" },
  { name: "canvasSet", sig: "canvasSet(buf, w, x, y, v)", doc: "Write v at normalized (x, y) on a row-major w-wide canvas (h = length/w). Coordinates clamp to the edges — no OOB, no *15.99 fudge. Returns v. (Luxel)" },
  { name: "canvasGet", sig: "canvasGet(buf, w, x, y)", doc: "Bilinear sample of a row-major w-wide canvas at normalized (x, y); texel centers at (i+0.5)/w, edges clamped. Smooth upscaling on larger maps for free. (Luxel)" },
  { name: "canvasAdd", sig: "canvasAdd(buf, w, x, y, v)", doc: "Add v into the cell canvasSet would write at normalized (x, y) — particle deposits without a manual read-modify-write. Same edge-clamped floor(x·w) addressing; returns the cell's new value. (Luxel)" },
  { name: "eventCount", sig: "eventCount()", doc: "Number of injected external events waiting to be read. Events arrive from preview clicks, POST /api/events, or any websocket/HTTP source. (Luxel)" },
  { name: "readEvent", sig: "readEvent(out)", doc: "Pop the oldest injected event into out[0..4] = [type, x, y, value] and return 1; returns 0 (out untouched) when none are queued. Idiom: while (readEvent(ev)) { … }. Preview clicks send type 1 with x/y normalized 0..1. (Luxel)" },
  { name: "dot", sig: "dot(x1, y1, x2, y2)", doc: "2D dot product. (Luxel)" },
  { name: "dot3", sig: "dot3(x1,y1,z1, x2,y2,z2)", doc: "3D dot product. (Luxel)" },
  { name: "angleBetween", sig: "angleBetween(x1, y1, x2, y2)", doc: "Signed angle from vector 1 to vector 2, radians (CCW positive). (Luxel)" },
  { name: "simplex2", sig: "simplex2(x, y, seed = 0)", doc: "2D simplex noise ~[-1,1] — smoother than perlin, no axis artifacts. (Luxel)" },
  { name: "simplex3", sig: "simplex3(x, y, z, seed = 0)", doc: "3D simplex noise ~[-1,1]. (Luxel)" },
  // randomness
  { name: "random", sig: "random(max)", doc: "True random in [0, max)." },
  { name: "prng", sig: "prng(max)", doc: "Seedable pseudo-random in [0, max)." },
  { name: "prngSeed", sig: "prngSeed(seed)", doc: "Seed prng() — xorshift32 over the seed's raw 16.16 word; returns the previous state (restore it to rewind the stream)." },
  { name: "randomSeed", sig: "randomSeed(seed)", doc: "Pin random()'s stream: same seed → same sequence on every Luxel device (splitmix64, pinned by test — for synced installations). Returns the previous seed. (Luxel)" },
  // waveforms & timing
  { name: "time", sig: "time(interval)", doc: "Sawtooth 0→1 every interval × 65.536 s." },
  { name: "wave", sig: "wave(v)", doc: "Sine shaped 0..1: (1 + sin(v·2π)) / 2." },
  { name: "square", sig: "square(v, duty)", doc: "Square wave 0/1 with given duty cycle." },
  { name: "triangle", sig: "triangle(v)", doc: "Triangle wave 0..1..0 per unit input." },
  { name: "timeScale", sig: "timeScale(s)", doc: "Run the pattern clock at s × real time — 0.25 slow-mo, 0 frozen, 2 double speed. time(), beat() and beforeRender's delta all follow. Returns the previous scale. (Luxel)" },
  { name: "setFrameRate", sig: "setFrameRate(fps)", doc: "Cap how often the pattern is evaluated: the last frame is held until 1000/fps ms have passed, then beforeRender gets the whole elapsed delta. 0 removes the cap; returns the previous one. (Luxel)" },
  // interpolation
  { name: "mix", sig: "mix(a, b, t)", doc: "Linear blend of a and b by t." },
  { name: "smoothstep", sig: "smoothstep(low, high, x)", doc: "Smooth 0..1 ramp between low and high." },
  { name: "bezierQuadratic", sig: "bezierQuadratic(t, p0, p1, p2)", doc: "Quadratic Bézier at t." },
  { name: "bezierCubic", sig: "bezierCubic(t, p0, p1, p2, p3)", doc: "Cubic Bézier at t." },
  // color output
  { name: "hsv", sig: "hsv(h, s, v)", doc: "Set the current pixel from hue/saturation/value (h wraps)." },
  { name: "hsv24", sig: "hsv24(h, s, v)", doc: "hsv() variant (24-bit path on PB; same output here)." },
  { name: "rgb", sig: "rgb(r, g, b)", doc: "Set the current pixel from red/green/blue 0..1." },
  { name: "oklch", sig: "oklch(l, c, h)", doc: "Set the pixel from perceptual OKLCH: lightness 0..1, chroma ~0..0.4, hue in turns. Smoother gradients than hsv. (Luxel)" },
  { name: "oklab", sig: "oklab(l, a, b)", doc: "Set the pixel from OKLab lightness/a/b. (Luxel)" },
  { name: "hsv2rgb", sig: "hsv2rgb(h, s, v, out)", doc: "Convert HSV to RGB into out[0..2] (returns out) — value form of hsv(). (Luxel)" },
  { name: "rgb2hsv", sig: "rgb2hsv(r, g, b, out)", doc: "Convert RGB to HSV into out[0..2] (returns out); hue in turns. (Luxel)" },
  { name: "mixColors", sig: "mixColors(r1,g1,b1, r2,g2,b2, t, out)", doc: "Blend two RGB colors in OKLab (perceptually even) into out[0..2]; returns out. (Luxel)" },
  { name: "setGamma", sig: "setGamma(g)", doc: "Output gamma applied after render (try 2.2 for perceptually even fades); 0 or 1 turns it off. (Luxel)" },
  { name: "setBlur", sig: "setBlur(amount, passes)", doc: "Post-process: blur the finished frame — in 2D (rows then columns) when the map is a regular matrix, along the pixel index otherwise. amount 0..1 is each neighbour's share (0.5 = the 1-2-1 kernel); passes 1..8 widens it. 0 turns it off. (Luxel)" },
  { name: "setGlow", sig: "setGlow(amount)", doc: "Post-process: bright pixels bleed `amount` of themselves into their neighbours, so highlights bloom without the frame losing energy. Two-dimensional on a matrix map, along the pixel index otherwise. 0 turns it off. (Luxel)" },
  { name: "setOutputPalette", sig: "setOutputPalette(pal, amount)", doc: "Post-process: recolor the finished frame by luma through a setPalette-format stop list — the pattern's structure, your palette's hues. amount 0..1 blends (default 1); a non-array argument turns it off. (Luxel)" },
  // arrays
  { name: "array", sig: "array(length)", doc: "Create a zero-filled array." },
  { name: "arrayLength", sig: "arrayLength(arr)", doc: "Number of elements in arr." },
  { name: "arraySum", sig: "arraySum(arr)", doc: "Sum of all elements." },
  { name: "arrayForEach", sig: "arrayForEach(arr, fn(v, i))", doc: "Call fn for each element." },
  { name: "arrayMutate", sig: "arrayMutate(arr, fn(v, i))", doc: "Replace each element with fn's result." },
  { name: "arrayMapTo", sig: "arrayMapTo(src, dest, fn(v, i))", doc: "Map src through fn into dest." },
  { name: "arrayReduce", sig: "arrayReduce(arr, fn(acc, v, i), initial)", doc: "Fold the array into one value." },
  { name: "arrayReplace", sig: "arrayReplace(arr, v1, v2, …)", doc: "Write the listed values into arr starting at index 0 — NOT a fill; arrayReplace(a, 0) sets only a[0]. Zero a whole buffer with feedback(a, 0)." },
  { name: "arrayReplaceAt", sig: "arrayReplaceAt(arr, index, value)", doc: "Set one element." },
  { name: "arraySort", sig: "arraySort(arr)", doc: "Sort ascending in place." },
  { name: "arraySortBy", sig: "arraySortBy(arr, fn(a, b))", doc: "Sort by comparator in place." },
  { name: "arrayAdd", sig: "arrayAdd(dst, src)", doc: "Element-wise dst[i] += src[i] over the shorter length, in place; returns dst. One VM call instead of an interpreted loop — the grid-simulation speedup. (Luxel)" },
  { name: "arraySub", sig: "arraySub(dst, src)", doc: "Element-wise dst[i] -= src[i] over the shorter length, in place; returns dst. (Luxel)" },
  { name: "arrayScale", sig: "arrayScale(arr, k)", doc: "Multiply every element by k in place (alias of feedback); returns arr. (Luxel)" },
  { name: "arrayMix", sig: "arrayMix(dst, src, t)", doc: "Element-wise dst[i] += (src[i] - dst[i])·t (unclamped lerp, like mix), in place; returns dst. t = 1 copies src into dst. (Luxel)" },
  // noise
  { name: "perlin", sig: "perlin(x, y, z, seed)", doc: "Perlin gradient noise ≈ -1..1." },
  { name: "perlinFbm", sig: "perlinFbm(x, y, z, lacunarity, gain, octaves)", doc: "Fractal Brownian motion over perlin." },
  { name: "perlinRidge", sig: "perlinRidge(x, y, z, lacunarity, gain, offset, octaves)", doc: "Ridged multifractal noise." },
  { name: "perlinTurbulence", sig: "perlinTurbulence(x, y, z, lacunarity, gain, octaves)", doc: "Turbulence (abs-valued fbm)." },
  { name: "setPerlinWrap", sig: "setPerlinWrap(x, y, z)", doc: "Make perlin tile with the given period." },
  // coordinate transforms (2D/3D mapped renders)
  { name: "resetTransform", sig: "resetTransform()", doc: "Clear the coordinate transform (it persists across frames)." },
  { name: "transform", sig: "transform(...16 values)", doc: "Set a full 4×4 transform matrix." },
  { name: "translate", sig: "translate(x, y)", doc: "Translate 2D map coordinates." },
  { name: "scale", sig: "scale(x, y)", doc: "Scale 2D map coordinates." },
  { name: "rotate", sig: "rotate(radians)", doc: "Rotate 2D map coordinates (counter-clockwise)." },
  { name: "translate3D", sig: "translate3D(x, y, z)", doc: "Translate 3D map coordinates." },
  { name: "scale3D", sig: "scale3D(x, y, z)", doc: "Scale 3D map coordinates." },
  { name: "rotateX", sig: "rotateX(radians)", doc: "Rotate 3D coordinates around X." },
  { name: "rotateY", sig: "rotateY(radians)", doc: "Rotate 3D coordinates around Y." },
  { name: "rotateZ", sig: "rotateZ(radians)", doc: "Rotate 3D coordinates around Z." },
  { name: "pixelMapDimensions", sig: "pixelMapDimensions()", doc: "Dimensions of the installed map (0/1/2/3)." },
  { name: "has2DMap", sig: "has2DMap()", doc: "1 if a 2D pixel map is installed." },
  { name: "has3DMap", sig: "has3DMap()", doc: "1 if a 3D pixel map is installed." },
  { name: "mapPixels", sig: "mapPixels(fn(index, x, y, z))", doc: "Iterate all pixels with mapped coordinates." },
  // palettes
  { name: "setPalette", sig: "setPalette(arr)", doc: "Install a gradient palette: [pos, r, g, b, …] stops." },
  { name: "paint", sig: "paint(t, brightness)", doc: "Set the current pixel from the palette at t." },
  // GPIO (stubs until a board wires them)
  { name: "pinMode", sig: "pinMode(pin, mode)", doc: "Configure a GPIO pin." },
  { name: "digitalWrite", sig: "digitalWrite(pin, value)", doc: "Drive a GPIO pin high/low." },
  { name: "digitalRead", sig: "digitalRead(pin)", doc: "Read a GPIO pin (0/1). No real GPIO yet — reads the idle level: 1 under INPUT_PULLUP, else 0." },
  { name: "analogRead", sig: "analogRead(pin)", doc: "Read an ADC pin 0..1." },
  { name: "touchRead", sig: "touchRead(pin)", doc: "Read a capacitive touch pin 0..1." },
  // clock (needs wall time; set via the host)
  { name: "clockYear", sig: "clockYear()", doc: "Current year." },
  { name: "clockMonth", sig: "clockMonth()", doc: "Month 1–12." },
  { name: "clockDay", sig: "clockDay()", doc: "Day of month 1–31." },
  { name: "clockHour", sig: "clockHour()", doc: "Hour 0–23." },
  { name: "clockMinute", sig: "clockMinute()", doc: "Minute 0–59." },
  { name: "clockSecond", sig: "clockSecond()", doc: "Second 0–59." },
  { name: "clockWeekday", sig: "clockWeekday()", doc: "Weekday 1–7 (1 = Sunday)." },
  // sequencer / playlist / identity
  { name: "sequencerNext", sig: "sequencerNext()", doc: "Advance to the next pattern." },
  { name: "sequencerGetMode", sig: "sequencerGetMode()", doc: "Current sequencer mode." },
  { name: "playlistGetPosition", sig: "playlistGetPosition()", doc: "Index of the playing playlist entry." },
  { name: "playlistSetPosition", sig: "playlistSetPosition(index)", doc: "Jump the playlist." },
  { name: "playlistGetLength", sig: "playlistGetLength()", doc: "Number of playlist entries." },
  { name: "nodeId", sig: "nodeId()", doc: "This device's id (for multi-device patterns)." },
];

/** Special globals available to patterns. */
export const GLOBALS: BuiltinDoc[] = [
  { name: "pixelCount", sig: "pixelCount", doc: "Number of pixels on the strip/matrix." },
  { name: "PI", sig: "PI", doc: "π (literal-quantized 16.16)." },
  { name: "PI2", sig: "PI2", doc: "2π." },
  { name: "PI3_4", sig: "PI3_4", doc: "3π/4." },
  { name: "PISQ", sig: "PISQ", doc: "π²." },
  { name: "E", sig: "E", doc: "Euler's number." },
  { name: "SQRT2", sig: "SQRT2", doc: "√2." },
  { name: "SQRT1_2", sig: "SQRT1_2", doc: "1/√2." },
  { name: "LN2", sig: "LN2", doc: "ln 2." },
  { name: "LN10", sig: "LN10", doc: "ln 10." },
  { name: "LOG2E", sig: "LOG2E", doc: "log₂ e." },
  { name: "LOG10E", sig: "LOG10E", doc: "log₁₀ e." },
  { name: "LOW", sig: "LOW", doc: "GPIO level 0." },
  { name: "HIGH", sig: "HIGH", doc: "GPIO level 1." },
  { name: "INPUT", sig: "INPUT", doc: "pinMode: input." },
  { name: "OUTPUT", sig: "OUTPUT", doc: "pinMode: output." },
  { name: "INPUT_PULLUP", sig: "INPUT_PULLUP", doc: "pinMode: input with pull-up." },
  { name: "INPUT_PULLDOWN", sig: "INPUT_PULLDOWN", doc: "pinMode: input with pull-down." },
  { name: "OUTPUT_OPEN_DRAIN", sig: "OUTPUT_OPEN_DRAIN", doc: "pinMode: open-drain output." },
  { name: "ANALOG", sig: "ANALOG", doc: "pinMode: analog." },
];
