#!/usr/bin/env python3
"""Compose → boot → assert the Pixelblaze v3 → Luxel takeover under emulation.

Hardware-free end-to-end test for the `pixelblaze-takeover` flavour of
`firmware/src/takeover.rs` (settings from Pixelblaze's SPIFFS `config.json`
via src/pbfs.rs, WiFi creds from its ESP-IDF NVS via src/pbnvs.rs).  The
exact analogue of `takeover-test.py` (the WLED one): builds a flash image in
the state a real Pixelblaze v3 is in the instant its OTA updater finishes
accepting a Luxel upload, boots it under Espressif's patched QEMU (see
docs/research/qemu-emulation-spike.md), and asserts on both the takeover's
serial narration and the resulting flash bytes.

The image under test is **stock** — the same `nix build .#luxel-fw-pixelblaze-v3`
output that ships.  Nothing here touches firmware source; the QEMU harness is
strictly isolated (CLAUDE.md hard rule).  The small parse/compose helpers are
deliberately DUPLICATED from takeover-test.py rather than shared, so neither
test can regress the other.

What it composes (4 MiB, from ONE gitignored dump — unlike the Athom there is
no separate filesystem image: the config AND the creds already live inside
the stock dump):

    0x000000  PB bootloader + PB partition table @0x8000       (from --stock)
    0x009000  nvs      0x5000  <- WiFi creds (pbnvs)
    0x00E000  otadata  0x2000  two entries, 0xE000 seq=1 / 0xF000 seq=2
    0x010000  app0     0x140000 (--slot app0 drops the OTA image here)
    0x150000  app1     0x140000 <- the Luxel OTA image, "PB just accepted it"
    0x290000  spiffs   0x170000 <- config.json (pbfs); ALSO where Luxel's
                                  `storage` lands after the takeover

The fixture's config: 180 px, ledType 2 (APA102/SK9822-class), colorOrder
GRB (-> Luxel sk9822 order code 4, "brg"), brightness 1.0 × maxBrightness
0.5 -> effective 128/255 -> Luxel 16/31.  No data pin (PB v3 hardwires
DATA=23/CLK=18 = this board's default), no power cap, no gamma.

THE DUMP CONTAINS REAL WIFI CREDENTIALS.  This test never prints, asserts on
or embeds the SSID or password: the serial assertions match PREFIXES of the
lines that carry the SSID, and the flash assertions check the LXCF record's
magic/version/lengths/checksum only.  Keep it that way (--keep leaves the
serial log and flash image in the work dir — treat both as secret).

Two variants:

    --slot app1  (default) the realistic post-upload state.  The dump's own
                 otadata already selects app1 (seq=2 at 0xF000); exercises
                 the full self-copy 0x150000 -> 0x10000.
    --slot app0  the image is already at the destination offset.  The
                 0xF000 entry is erased so the dump's seq=1 at 0xE000 selects
                 app0.  Exercises the "skip the copy" path.

One QEMU invocation covers both boots: the takeover ends in `software_reset()`,
which reboots in-process.  Boot 2 reaches WiFi init and then panics inside the
esp-radio PHY blob (an unmodelled peripheral alias, expected and documented in
the spike), so QEMU is killed the instant boot 2 prints the inheritance proof
(`wifi: creds from flash (` — prefix only, the rest is the SSID); letting it
run on would give `custom_halt` its reboot and a further boot whose
`ota::boot_guard` would rewrite otadata and ruin the flash diff.

Usage:
    nix build .#luxel-fw-pixelblaze-v3 --out-link result-pb
    nix develop -c python3 tools/qemu/pb-takeover-test.py \
        --stock /path/to/pb-v3-stock.bin --result-dir result-pb

    tools/qemu/pb-takeover-test.py --slot app0 --keep

`--qemu` defaults to auto-resolving the emulator through nix (the flake's
`qemu-espressif` output, falling back to the `--impure` expression path).
The eFuse image is generated by `tools/qemu/make-efuse.py`.

Exit 0 with a PASS summary listing every assertion; nonzero on the first
failure, with a tail of the serial log (which may contain the SSID — it is
the firmware's own narration, shown only on failure, to stderr).
"""

from __future__ import annotations

import argparse
import os
import re
import shutil
import struct
import subprocess
import sys
import tempfile
import time
import zlib

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.dirname(os.path.dirname(HERE))

FLASH_SIZE = 4 * 1024 * 1024
TABLE_OFFSET = 0x8000
TABLE_LEN = 0x100
# Pixelblaze v3's table (read out of the dump, see the docstring).
PB_OTADATA_0 = 0x0E000  # first entry of PB's otadata partition (0xE000/0x2000)
PB_OTADATA_1 = 0x0F000  # second entry
APP0 = 0x10000
APP1 = 0x150000
APP_LEN = 0x140000
PB_SPIFFS = 0x290000
# Luxel's 4 MB table (partitions.csv): the takeover installs it directly.
LXCF_OFFSET = 0x9000  # config.rs RECORD_OFFSET
LXDV_OFFSET = 0xA000  # config.rs DEV_OFFSET
DEV_VER = 8  # config.rs DEV_VER (v8 took a v7 pad byte for the data pin)
LXBG_OFFSET = 0xC000  # ota.rs GUARD_OFFSET (4th nvs sector under both layouts)
LUXEL_OTADATA = 0xD000  # partitions.csv: otadata, 0xd000, 0x2000
LUXEL_STORAGE = 0x290000  # partitions.csv: storage, 0x290000, 0x80000
SECTOR = 0x1000
ESP_OTA_IMG_VALID = 2

# What the fixture's config.json maps to (takeover.rs inherit_device +
# pbfs.rs).  The brightness is 1.0 × maxBrightness 0.5: 255 × 128 -> 128/255
# -> round(128 × 31 / 255) = 16/31.
PIXELS = 180
PROTO_CODE = 0          # sk9822 (leds::Protocol)
PROTO_NAME = "sk9822"
ORDER_CODE = 4          # PB "GRB" on an SK9822 (native bgr) -> Luxel "brg"
ORDER_NAME = "brg"
BRI_255, MAXBRI_255, EFF_255 = 255, 128, 128
BRIGHTNESS = 16
CAP_MA = 0
GAMMA_TENTHS = 0

# Any of these in the serial log means the takeover bailed out; fail fast
# rather than burning the full timeout waiting for a marker that won't come.
ABORT_MARKERS = (
    "takeover: verify failed at",
    "takeover: read failed at",
    "takeover: copy failed",
    "partitions: flash too small",
    "takeover: own image not found",
    "takeover: cannot size own image",
    "takeover: config wipe failed",
    "takeover: creds carry-over failed",
    "takeover: settings carry-over failed",
    "takeover: TABLE WRITE FAILED",
    "takeover: no ota_0 in embedded table",
    "consecutive failed boots — rolling back",
)

ABORT_HINTS = {
    "partitions: flash too small": (
        "this is a NEW QEMU divergence, not a firmware bug: esp-storage's "
        "FlashStorage::capacity() has previously reported the real 4 MiB "
        "under emulation.  Report it rather than working around it."
    ),
}

REBOOT_LINE = "takeover: partition table installed — rebooting into Luxel"
# Prefixes only — the rest of each line is the SSID, which never appears here.
INHERIT_PREFIX = 'takeover: inherited WiFi credentials for "'
KILL_PREFIX = 'wifi: creds from flash ("'
FORMAT_LINE = re.compile(r"patterns: format \d+ != \d+, wiping storage")
# Firmware lines that spell the SSID out; the failure-path serial tail cuts
# each at its prefix so the dump's real network name never reaches a log.
SECRET_PREFIXES = (INHERIT_PREFIX, KILL_PREFIX, 'wifi: joining "')


class Fail(Exception):
    pass


# --------------------------------------------------------------------------
# compose


def otadata_entry(seq: int) -> bytes:
    """One 32-byte ESP-IDF otadata entry selecting OTA slot `(seq - 1) % n`.

    Layout (`esp_ota_select_entry_t`): u32 seq, 20 bytes label, 4 bytes
    ota_state, u32 crc.  The CRC is over the 4 seq bytes only, zlib crc32 with
    an all-ones initial value (ESP-IDF `bootloader_common_ota_select_crc`).
    Unwritten fields stay erased (0xFF) exactly as esp_ota_set_boot_partition
    leaves them for a non-rollback build.
    """
    crc = zlib.crc32(struct.pack("<I", seq), 0xFFFFFFFF) & 0xFFFFFFFF
    return struct.pack("<I", seq) + b"\xff" * 24 + struct.pack("<I", crc)


def check_fixture(stock: bytes) -> None:
    """The dump has to be a Pixelblaze v3 flash image — sanity-check the
    bits this test's offsets are derived from, without touching NVS."""
    if len(stock) != FLASH_SIZE:
        raise Fail(f"--stock is {len(stock)} B, expected {FLASH_SIZE}")
    want = {
        b"nvs": (0x9000, 0x5000), b"otadata": (0xE000, 0x2000),
        b"app0": (APP0, APP_LEN), b"app1": (APP1, APP_LEN),
        b"spiffs": (PB_SPIFFS, 0x170000),
    }
    got = {}
    t = stock[TABLE_OFFSET : TABLE_OFFSET + TABLE_LEN]
    for i in range(0, TABLE_LEN, 32):
        e = t[i : i + 32]
        if e[:2] != b"\xaa\x50":
            break
        off, ln = struct.unpack_from("<II", e, 4)
        got[e[12:28].rstrip(b"\0")] = (off, ln)
    if got != want:
        raise Fail(f"--stock: not the Pixelblaze v3 table at 0x8000: {got}")
    if stock[APP1 : APP1 + 1] != b"\xe9":
        raise Fail("--stock: no app image in app1 — is this the stock PB dump?")
    if stock[PB_SPIFFS : PB_SPIFFS + SECTOR] == b"\xff" * SECTOR:
        raise Fail("--stock: spiffs at 0x290000 is erased — no config.json to inherit")


def compose(stock: bytes, ota: bytes, slot: str) -> bytearray:
    check_fixture(stock)
    if ota[:1] != b"\xe9":
        raise Fail("result/luxel-fw-ota.bin does not start with the 0xE9 image magic")
    if len(ota) > APP_LEN:
        raise Fail(f"the {len(ota)} B app image does not fit a {APP_LEN:#x} B PB slot")

    img = bytearray(stock)
    if slot == "app1":
        img[APP1 : APP1 + len(ota)] = ota
        # PB's first otadata entry (0xE000, seq=1) stays valid and untouched;
        # the higher sequence number in the second entry wins, so the stock
        # bootloader boots app1 — the dump already has this, rewrite it so
        # the test does not depend on the dump's history.
        img[PB_OTADATA_1 : PB_OTADATA_1 + 32] = otadata_entry(2)
    else:
        img[APP0 : APP0 + len(ota)] = ota
        # Select app0: entry #0 seq=1, entry #1 erased (the dump's seq=2
        # there would otherwise win).
        img[PB_OTADATA_0 : PB_OTADATA_0 + 32] = otadata_entry(1)
        img[PB_OTADATA_1 : PB_OTADATA_1 + SECTOR] = b"\xff" * SECTOR
    return img


# --------------------------------------------------------------------------
# emulator


def resolve_qemu(explicit: str | None) -> str:
    if explicit:
        cand = explicit
        if os.path.isdir(cand):
            cand = os.path.join(cand, "bin", "qemu-system-xtensa")
        if not os.access(cand, os.X_OK):
            raise Fail(f"--qemu {explicit}: no executable qemu-system-xtensa")
        return cand

    attempts = [
        ["nix", "build", "--no-link", "--print-out-paths", f"{REPO}#qemu-espressif"],
        [
            "nix", "build", "--no-link", "--print-out-paths", "--impure",
            "--expr", f"import {HERE}/qemu-espressif.nix {{}}",
        ],
    ]
    errors = []
    for cmd in attempts:
        p = subprocess.run(cmd, capture_output=True, text=True)
        if p.returncode == 0 and p.stdout.strip():
            out = p.stdout.strip().splitlines()[-1]
            binary = os.path.join(out, "bin", "qemu-system-xtensa")
            if os.access(binary, os.X_OK):
                return binary
            errors.append(f"{out} has no bin/qemu-system-xtensa")
        else:
            errors.append(p.stderr.strip().splitlines()[-1] if p.stderr.strip() else "nix build failed")
    raise Fail("could not resolve qemu-espressif:\n  " + "\n  ".join(errors))


def make_efuse(path: str) -> None:
    p = subprocess.run(
        [sys.executable, os.path.join(HERE, "make-efuse.py"), "-o", path],
        capture_output=True,
        text=True,
    )
    if p.returncode != 0:
        raise Fail(f"make-efuse.py failed:\n{p.stderr}")


def reached_marker(text: str) -> bool:
    """Boot 2 has printed its creds-from-flash line (prefix match: the SSID
    follows and is never spelled out here)."""
    return REBOOT_LINE in text and KILL_PREFIX in text.split(REBOOT_LINE)[-1]


def run_qemu(qemu: str, flash: str, efuse: str, log: str, timeout: float) -> tuple[str, float]:
    """Boot the composed image; return (serial log, wall seconds).

    Marker-driven: returns as soon as boot 2 proves credential inheritance.
    NOTE the flash drive deliberately has no `snapshot=on` — the post-run
    assertions diff the file QEMU wrote.
    """
    cmd = [
        qemu, "-display", "none", "-monitor", "none", "-machine", "esp32",
        "-drive", f"file={flash},if=mtd,format=raw",
        "-drive", f"file={efuse},if=none,format=raw,id=efuse,snapshot=on",
        "-global", "driver=nvram.esp32.efuse,property=drive,value=efuse",
        "-serial", f"file:{log}",
    ]
    open(log, "wb").close()
    start = time.monotonic()
    with open(os.devnull, "rb") as devnull:
        proc = subprocess.Popen(cmd, stdin=devnull, stdout=subprocess.DEVNULL,
                                stderr=subprocess.PIPE)
        text = ""
        outcome = None
        try:
            while True:
                with open(log, "rb") as f:
                    text = f.read().decode("utf-8", "replace")
                if reached_marker(text):
                    outcome = "marker"
                    break
                for m in ABORT_MARKERS:
                    if m in text:
                        outcome = f"abort line: {m.strip()}"
                        if m in ABORT_HINTS:
                            outcome += f"\n  {ABORT_HINTS[m]}"
                        break
                if outcome:
                    break
                if proc.poll() is not None:
                    outcome = f"qemu exited early (rc={proc.returncode})"
                    break
                if time.monotonic() - start > timeout:
                    outcome = f"timeout after {timeout:.0f}s"
                    break
                time.sleep(0.25)
        finally:
            if proc.poll() is None:
                proc.terminate()
                try:
                    proc.wait(timeout=10)
                except subprocess.TimeoutExpired:
                    proc.kill()
                    proc.wait()
    elapsed = time.monotonic() - start
    with open(log, "rb") as f:
        text = f.read().decode("utf-8", "replace")
    if outcome != "marker":
        stderr = proc.stderr.read().decode("utf-8", "replace") if proc.stderr else ""
        raise Fail(f"boot did not reach the success marker — {outcome}"
                   + (f"\nqemu stderr:\n{stderr.strip()}" if stderr.strip() else ""))
    return text, elapsed


# --------------------------------------------------------------------------
# assertions


class Checks:
    def __init__(self) -> None:
        self.passed: list[str] = []

    def ok(self, what: str) -> None:
        self.passed.append(what)

    def require(self, cond: bool, what: str, detail: str = "") -> None:
        if not cond:
            raise Fail(f"{what}\n  {detail}" if detail else what)
        self.ok(what)

    def line(self, hay: str, needle: str, where: str) -> None:
        self.require(needle in hay, f"serial[{where}]: {needle!r}",
                     f"not found in the {where} section of the log")


def check_serial(log: str, slot: str, ota_len: int, c: Checks) -> None:
    if REBOOT_LINE not in log:
        raise Fail("takeover never reached the table rewrite")
    boot1, boot2 = log.split(REBOOT_LINE, 1)

    c.line(boot1, "takeover: foreign partition table at 0x8000 — installing Luxel layout", "boot1")
    c.line(boot1, INHERIT_PREFIX, "boot1")  # prefix: the SSID follows, unchecked
    c.require("takeover: no WiFi credentials to inherit" not in boot1,
              "serial[boot1]: NVS creds were found (no provisioning-AP fallback)",
              "the takeover found no creds in Pixelblaze's NVS")
    c.require("takeover: no LED wiring to inherit" not in boot1,
              "serial[boot1]: config.json wiring was found (no board-defaults fallback)",
              "the takeover found no wiring in Pixelblaze's spiffs")
    if slot == "app1":
        c.line(boot1, f"takeover: copying {ota_len} B {APP1:#x} → {APP0:#x}", "boot1")
        # copy_region() narrates every 64th sector; the last such line is the
        # progress proof that the whole image went through the verify loop.
        sectors = -(-ota_len // SECTOR)
        total_kib = sectors * SECTOR // 1024
        last = ((sectors - 1) // 64) * 64 * SECTOR // 1024
        c.line(boot1, f"takeover: copied {last}/{total_kib} KiB", "boot1")
    else:
        c.line(boot1, f"takeover: image already in place at {APP0:#x}", "boot1")
    c.line(boot1, f"takeover: Pixelblaze ran at brightness {BRI_255}/255 × limit "
                  f"{MAXBRI_255}/255 → effective {EFF_255}/255", "boot1")
    c.line(boot1, "takeover: wiping config/otadata sectors 0x9000..0x10000", "boot1")
    c.line(boot1, "takeover: WiFi credentials carried over", "boot1")
    c.line(boot1,
           f"takeover: settings carried over ({PIXELS} px, {PROTO_NAME}, order {ORDER_NAME}, "
           f"brightness {BRIGHTNESS}/31, cap {CAP_MA} mA, gamma "
           f"{GAMMA_TENTHS // 10}.{GAMMA_TENTHS % 10})", "boot1")
    c.ok(f"serial[boot1]: {REBOOT_LINE!r}")

    c.line(boot2, "booted from: ota_0", "boot2")
    # A taken-over device runs ota_0 under Luxel's 4 MB table; the first
    # Luxel OTA must go to that table's ota_1 (0x150000), not over the code
    # it is running (Gitea #655).  ota::init prints the choice every boot.
    c.line(boot2, "ota: updates go to ota_1 at 0x150000", "boot2")
    c.require("ota: updates go to ota_0 at" not in boot2,
              "serial[boot2]: the running slot is never the OTA target",
              "ota::init named ota_0 while executing from it")
    # Luxel's `storage` lands on top of PB's spiffs: whatever the map reader
    # makes of that, it is not the current format, and the store is wiped.
    m = FORMAT_LINE.search(boot2)
    c.require(m is not None, "serial[boot2]: 'patterns: format <n> != <cur>, wiping storage'",
              "the pattern store did not announce a wipe of the old spiffs region")
    c.line(boot2, f"(storage @ {LUXEL_STORAGE:#x})", "boot2")
    c.line(boot2, KILL_PREFIX, "boot2")  # prefix: the SSID follows, unchecked


def check_flash(flash: bytes, expected_table: bytes, ota: bytes, slot: str, c: Checks) -> None:
    got = flash[TABLE_OFFSET : TABLE_OFFSET + TABLE_LEN]
    c.require(got == expected_table, "flash: Luxel partition table installed at 0x8000",
              f"first differing byte at {first_diff(got, expected_table)}")

    check_lxcf(flash, c)
    check_lxdv(flash, c)

    got = flash[APP0 : APP0 + len(ota)]
    c.require(got == ota, f"flash: ota_0 (0x10000) holds the {len(ota)} B app image byte-for-byte",
              f"first differing byte at {first_diff(got, ota)}")

    if slot == "app1":
        # The takeover never writes to its source, and nothing else does
        # either: Luxel's `storage` starts at 0x290000, which is exactly
        # where PB's app1 slot ends, so the whole copy source survives.
        got = flash[APP1 : APP1 + len(ota)]
        c.require(got == ota, f"flash: copy source {APP1:#x} left wholly untouched",
                  f"first differing byte at {first_diff(got, ota)}")
        c.require(APP1 + len(ota) <= LUXEL_STORAGE,
                  f"flash: PB's app1 image ends at {APP1 + len(ota):#x}, at or below "
                  f"the new `storage` at {LUXEL_STORAGE:#x}",
                  "the app image has grown into the storage partition")

    # Luxel's `storage` is PB's spiffs region.  Boot 2's pattern store finds
    # no (valid) format marker there, wipes the key area and writes its own
    # — so the region is no longer PB's config data.  That is the proof the
    # NEW table took effect.
    key_area = flash[LUXEL_STORAGE : LUXEL_STORAGE + SECTOR]
    c.require(any(b != 0xFF for b in key_area),
              f"flash: the new `storage` key area at {LUXEL_STORAGE:#x} was "
              "formatted by the pattern store",
              "still erased — did the new table take effect?")

    # 0xC000 is the boot-guard sector (ota.rs GUARD_OFFSET), inside the wiped
    # range but rewritten by boot 2's `boot_guard()` before the takeover check
    # even runs.  So it is NOT erased: expect the record, attempt count 1.
    guard = flash[LXBG_OFFSET : LXBG_OFFSET + 8]
    c.require(guard[0:4] == b"LXBG" and guard[4] == 1 and guard[5] == 0,
              "flash: boot-guard record at 0xC000 (LXBG, 1 attempt, no force-AP)",
              f"got {guard.hex()}")
    # byte 6 is the takeover reboot-to-retry counter (issue #35); a successful
    # takeover wipes the sector, so it must not leak into the final state.
    c.require(guard[6] == 0, "flash: takeover retry counter cleared (guard byte 6)",
              f"got {guard[6]}")

    # 0xD000 is Luxel's otadata.  The takeover wipes it, so the next boot's
    # ESP-IDF second-stage bootloader finds both entries erased, falls back to
    # ota_0 — and *writes the choice back* (`set_actual_ota_seq()`: seq =
    # index + 1, ota_state = ESP_OTA_IMG_VALID, CRC over the seq word).  So
    # "erased" is the wrong expectation here; this is the observed and correct
    # post-fallback state.  0xE000 was PB's otadata — wiped, and still erased.
    ota0 = flash[LUXEL_OTADATA : LUXEL_OTADATA + 32]
    seq, = struct.unpack("<I", ota0[0:4])
    state, crc = struct.unpack("<II", ota0[24:32])
    want_crc = zlib.crc32(ota0[0:4], 0xFFFFFFFF) & 0xFFFFFFFF
    c.require(seq == 1 and state == ESP_OTA_IMG_VALID and crc == want_crc,
              "flash: otadata 0xD000 rewritten by the bootloader as seq=1/VALID (-> ota_0)",
              f"seq={seq} state={state} crc={crc:#010x} want {want_crc:#010x} raw={ota0.hex()}")
    ota1 = flash[LUXEL_OTADATA + SECTOR : LUXEL_OTADATA + SECTOR + 32]
    c.require(ota1 == b"\xff" * 32,
              "flash: otadata entry #1 (0xE000, PB's old otadata) still erased",
              f"got {ota1.hex()}")


def check_lxcf(flash: bytes, c: Checks) -> None:
    """The inherited-credentials record written by config::write_wifi().

    Validity, lengths and checksum ONLY — the ssid/password bytes are real
    and are never decoded, compared or printed."""
    rec = flash[LXCF_OFFSET : LXCF_OFFSET + SECTOR]
    c.require(rec[0:4] == b"LXCF", "flash: LXCF creds record at 0x9000", f"got {rec[0:8].hex()}")
    ver, slen, plen, pad = rec[4], rec[5], rec[6], rec[7]
    c.require(ver == 1 and pad == 0, "flash: LXCF version 1", f"ver={ver} pad={pad}")
    c.require(1 <= slen <= 32, "flash: inherited ssid length in 1..=32", f"got {slen}")
    c.require(plen <= 64, "flash: inherited password length <= 64", f"got {plen}")
    end = 8 + slen + plen
    stored = struct.unpack("<I", rec[end : end + 4])[0]
    want = sum(rec[:end]) & 0xFFFFFFFF  # config.rs: wrapping u32 byte sum
    c.require(stored == want, "flash: LXCF checksum valid",
              f"stored {stored:#010x} want {want:#010x}")
    tail = rec[end + 4 :]
    c.require(tail == b"\xff" * len(tail), "flash: rest of the 0x9000 sector erased",
              f"first non-0xFF at {first_diff(tail, b'\xff' * len(tail))}")


def check_lxdv(flash: bytes, c: Checks) -> None:
    """The inherited-wiring record written by config::write_device() —
    values are the fixture's config.json (see the module docstring).

    Byte 21 is v8's data pin, stored as pin+1 so 0 means "board default"
    (config.rs); PB v3 hardwires its LED pins to this board's default, so
    the takeover stores no override."""
    rec = flash[LXDV_OFFSET : LXDV_OFFSET + SECTOR]
    c.require(rec[0:4] == b"LXDV", "flash: LXDV device-config record at 0xA000",
              f"got {rec[0:8].hex()}")
    ver, bri, proto, sync = rec[4], rec[5], rec[6], rec[7]
    c.require(ver == DEV_VER, f"flash: LXDV version {DEV_VER}", f"ver={ver}")
    pixels = struct.unpack("<I", rec[8:12])[0]
    tz = struct.unpack("<h", rec[12:14])[0]
    order, gamma = rec[14], rec[15]
    cap = struct.unpack("<H", rec[16:18])[0]
    c.require(pixels == PIXELS, f"flash: imported pixel count {PIXELS}", f"got {pixels}")
    c.require(proto == PROTO_CODE,
              f"flash: imported protocol {PROTO_NAME} (code {PROTO_CODE}, PB ledType 2)",
              f"got {proto}")
    c.require(order == ORDER_CODE,
              f"flash: imported color order {ORDER_NAME} (code {ORDER_CODE}, PB colorOrder GRB)",
              f"got {order}")
    c.require(bri == BRIGHTNESS,
              f"flash: imported brightness {BRIGHTNESS}/31 (PB 1.0 × limit 0.5 = {EFF_255}/255)",
              f"got {bri}")
    c.require(cap == CAP_MA, f"flash: power cap {CAP_MA} mA (PB has none)", f"got {cap}")
    c.require(gamma == GAMMA_TENTHS, "flash: gamma 0.0 (PB exposes none)", f"got {gamma}")
    curve, blur, glow = rec[18], rec[19], rec[20]
    c.require(sync == 0 and tz == 0 and rec[22:24] == b"\x00\x00",
              "flash: LXDV non-imported fields at defaults",
              f"sync={sync} tz={tz} pad={rec[22:24].hex()}")
    stored_pin = rec[21]
    c.require(stored_pin == 0,
              "flash: LXDV data pin 0 = board default (PB v3 pins are hardwired)",
              f"got byte {stored_pin} (= GPIO{stored_pin - 1})")
    c.require(curve == 0 and blur == 0 and glow == 0,
              "flash: post-process chain off (PB has no equivalent)",
              f"curve={curve} blur={blur} glow={glow}")
    stored = struct.unpack("<I", rec[24:28])[0]
    want = sum(rec[:24]) & 0xFFFFFFFF  # config.rs: wrapping u32 byte sum
    c.require(stored == want, "flash: LXDV checksum valid",
              f"stored {stored:#010x} want {want:#010x}")
    tail = rec[28:]
    c.require(tail == b"\xff" * len(tail), "flash: rest of the 0xA000 sector erased",
              f"first non-0xFF at {first_diff(tail, b'\xff' * len(tail))}")


def redact(line: str) -> str:
    for p in SECRET_PREFIXES:
        i = line.find(p)
        if i >= 0:
            return line[: i + len(p)] + "<redacted>"
    return line


def first_diff(a: bytes, b: bytes) -> str:
    n = min(len(a), len(b))
    for i in range(n):
        if a[i] != b[i]:
            return f"+{i:#x} ({a[i]:#04x} != {b[i]:#04x})"
    return f"length {len(a)} != {len(b)}"


# --------------------------------------------------------------------------


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--stock", required=True, help="pb-v3-stock.bin (4 MiB full dump)")
    ap.add_argument("--result-dir", default="result",
                    help="nix build .#luxel-fw-pixelblaze-v3 output (default ./result)")
    ap.add_argument("--qemu", help="qemu-system-xtensa (or its store dir); default: nix build")
    ap.add_argument("--slot", choices=("app0", "app1"), default="app1",
                    help="which PB app slot receives the upload (default app1)")
    ap.add_argument("--workdir", help="where to compose (default: a temp dir)")
    ap.add_argument("--keep", action="store_true",
                    help="keep the work dir on success (its serial log and flash "
                         "image carry the dump's real WiFi creds)")
    ap.add_argument("--timeout", type=float, default=300.0,
                    help="overall boot timeout in seconds (default 300)")
    args = ap.parse_args(argv)

    workdir = args.workdir or tempfile.mkdtemp(prefix="luxel-pb-takeover-")
    os.makedirs(workdir, exist_ok=True)
    log = os.path.join(workdir, "serial.log")
    try:
        rc = run(args, workdir, log)
    except Fail as e:
        print(f"\nFAIL [{args.slot}]: {e}", file=sys.stderr)
        if os.path.exists(log):
            with open(log, "rb") as f:
                tail = f.read().decode("utf-8", "replace").splitlines()[-40:]
            print("\n--- serial tail (SSID-bearing lines redacted) ---", file=sys.stderr)
            print("\n".join(redact(l) for l in tail), file=sys.stderr)
        print(f"\nwork dir kept: {workdir}", file=sys.stderr)
        return 1
    if args.keep or args.workdir:
        print(f"work dir: {workdir}")
    else:
        shutil.rmtree(workdir, ignore_errors=True)
    return rc


def run(args: argparse.Namespace, workdir: str, log: str) -> int:
    ota_path = os.path.join(args.result_dir, "luxel-fw-ota.bin")
    merged_path = os.path.join(args.result_dir, "luxel-fw.bin")
    for p in (args.stock, ota_path, merged_path):
        if not os.path.exists(p):
            built = p in (ota_path, merged_path)
            raise Fail(f"missing input: {p}"
                       + ("\n  run: nix build .#luxel-fw-pixelblaze-v3" if built else ""))

    stock = open(args.stock, "rb").read()
    ota = open(ota_path, "rb").read()
    # Same build for both: the takeover matches the 256-byte esp_app_desc
    # (build timestamp included) at slot+0x20 against the running image.
    expected_table = open(merged_path, "rb").read()[TABLE_OFFSET : TABLE_OFFSET + TABLE_LEN]

    print(f"== Pixelblaze takeover test, --slot {args.slot} ==")
    print(f"   app image : {ota_path} ({len(ota)} B)")
    print(f"   work dir  : {workdir}")

    img = compose(stock, ota, args.slot)
    flash = os.path.join(workdir, "flash.bin")
    with open(flash, "wb") as f:
        f.write(img)
    efuse = os.path.join(workdir, "efuse.bin")
    make_efuse(efuse)

    qemu = resolve_qemu(args.qemu)
    print(f"   qemu      : {qemu}")
    print("   booting…")
    text, elapsed = run_qemu(qemu, flash, efuse, log, args.timeout)
    print(f"   reached the inheritance marker in {elapsed:.1f}s wall")

    c = Checks()
    check_serial(text, args.slot, len(ota), c)
    with open(flash, "rb") as f:
        written = f.read()
    check_flash(written, expected_table, ota, args.slot, c)

    print(f"\nPASS [{args.slot}] — {len(c.passed)} assertions in {elapsed:.1f}s")
    for a in c.passed:
        print(f"  ok  {a}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
