#!/usr/bin/env python3
"""Compose → boot → assert the WLED→Luxel takeover under emulation.

Hardware-free end-to-end test for `firmware/src/takeover.rs`: builds a flash
image in exactly the state a real Athom is in the instant WLED's OTA updater
finishes accepting a Luxel upload, boots it under Espressif's patched QEMU
(see docs/research/qemu-emulation-spike.md), and asserts on both the takeover's
serial narration and the resulting flash bytes.

The image under test is **stock** — the same `nix build .#luxel-fw-athom-music`
output that ships. Nothing here touches firmware source; the QEMU harness is
strictly isolated (CLAUDE.md hard rule).

What it composes (4 MiB, from the two gitignored dumps in the main checkout):

    0x000000  WLED bootloader + WLED partition table @0x8000   (from --stock)
    0x00F000  WLED otadata entry #1: seq=2 -> boots app1        (--slot app1)
    0x010000  app0  (--slot app0 drops the OTA image here instead)
    0x190000  app1  <- the Luxel OTA image, "WLED just accepted the upload"
    0x310000  configured WLED littlefs, ssid "MOMCorp Intranet" (from --fs)

Two variants:

    --slot app1  (default) the realistic post-upload state.  Exercises the full
                 920 KiB self-copy 0x190000 -> 0x10000, which is where issue
                 #35's verify flake lives.
    --slot app0  the image is already at the destination offset.  Exercises the
                 "skip the copy" path.

One QEMU invocation covers both boots: the takeover ends in `software_reset()`,
which reboots in-process.  Boot 2 reaches WiFi init and then panics inside the
esp-radio PHY blob (LoadStoreAddrError @0x60008000 — an unmodelled peripheral
alias, expected and documented in the spike).  We therefore kill QEMU the
instant boot 2 prints the inheritance proof; letting it run on would give
`custom_halt` its 3 s reboot and a further boot, whose `ota::boot_guard` would
rewrite otadata and ruin the flash diff.

QEMU quirk you will see in the log: the SW_RESET boot that `software_reset()`
triggers dies partway through the ROM banner ("mode:DOUT, clock div:" and
nothing more), the TG0 watchdog fires, and *that* reset is the one that
actually loads Luxel.  It happens before the second-stage bootloader touches
anything, so it is cosmetic — hardware reboots straight through.  The
assertions key off takeover output, not reset counts, so it doesn't matter.

Inputs (gitignored — they live in the main checkout, never commit them):

    --stock  athom-wled-stock.bin        4 MiB full stock Athom flash dump
    --fs     athom-wled-fs-configured.bin  983040 B configured WLED littlefs

Usage:
    nix build .#luxel-fw-athom-music
    nix develop -c python3 tools/qemu/takeover-test.py \
        --stock /path/to/athom-wled-stock.bin \
        --fs    /path/to/athom-wled-fs-configured.bin

    tools/qemu/takeover-test.py --slot app0 --keep

`--qemu` defaults to auto-resolving the emulator through nix (the flake's
`qemu-espressif` output, falling back to the `--impure` expression path).
The eFuse image is generated by `tools/qemu/make-efuse.py` (chip rev 3.0 —
esp-hal's runtime revision gate rejects QEMU's all-zero eFuses).

Exit 0 with a PASS summary listing every assertion; nonzero on the first
failure, with a tail of the serial log.
"""

from __future__ import annotations

import argparse
import os
import shutil
import struct
import subprocess
import sys
import tempfile
import time
import zlib

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.dirname(os.path.dirname(HERE))

FLASH_SIZE = 4 * 1024 * 1024
TABLE_OFFSET = 0x8000
TABLE_LEN = 0x100
WLED_OTADATA_1 = 0x0F000  # second entry of WLED's otadata partition (0xE000/0x2000)
APP0 = 0x10000
APP1 = 0x190000
FS_OFFSET = 0x310000
LXCF_OFFSET = 0x9000  # config.rs RECORD_OFFSET
LXBG_OFFSET = 0xC000  # ota.rs GUARD_OFFSET (4th nvs sector under both layouts)
LUXEL_OTADATA = 0xD000  # partitions.csv: otadata, 0xd000, 0x2000
LUXEL_STORAGE = 0x210000  # partitions.csv: storage, 0x210000, 0x100000
SECTOR = 0x1000
ESP_OTA_IMG_VALID = 2

SSID = "MOMCorp Intranet"
PASS_LEN = 20

# Any of these in the serial log means the takeover bailed out; fail fast
# rather than burning the full timeout waiting for a marker that won't come.
ABORT_MARKERS = (
    "takeover: verify failed at",
    "takeover: read failed at",
    "takeover: copy failed",
    "takeover: flash too small",
    "takeover: own image not found",
    "takeover: cannot size own image",
    "takeover: config wipe failed",
    "takeover: creds carry-over failed",
    "takeover: TABLE WRITE FAILED",
    "takeover: no ota_0 in embedded table",
    "consecutive failed boots — rolling back",
)

# Markers that mean something more specific than "the takeover gave up".
ABORT_HINTS = {
    "takeover: flash too small": (
        "this is a NEW QEMU divergence, not a firmware bug: esp-storage's "
        "FlashStorage::capacity() has previously reported the real 4 MiB "
        "under emulation.  Report it rather than working around it."
    ),
}

REBOOT_LINE = "takeover: partition table installed — rebooting into Luxel"
KILL_MARKER = f'wifi: creds from flash ("{SSID}")'


class Fail(Exception):
    pass


# --------------------------------------------------------------------------
# compose


def otadata_entry(seq: int) -> bytes:
    """One 32-byte ESP-IDF otadata entry selecting OTA slot `(seq - 1) % n`.

    Layout (`esp_ota_select_entry_t`): u32 seq, 20 bytes label, 4 bytes
    ota_state, u32 crc.  The CRC is over the 4 seq bytes only, zlib crc32 with
    an all-ones initial value (ESP-IDF `bootloader_common_ota_select_crc`).
    Unwritten fields stay erased (0xFF) exactly as esp_ota_set_boot_partition
    leaves them for a non-rollback build.
    """
    crc = zlib.crc32(struct.pack("<I", seq), 0xFFFFFFFF) & 0xFFFFFFFF
    return struct.pack("<I", seq) + b"\xff" * 24 + struct.pack("<I", crc)


def compose(stock: bytes, fs: bytes, ota: bytes, slot: str) -> bytearray:
    if len(stock) != FLASH_SIZE:
        raise Fail(f"--stock is {len(stock)} B, expected {FLASH_SIZE}")
    if FS_OFFSET + len(fs) > FLASH_SIZE:
        raise Fail(f"--fs is {len(fs)} B, too big for the spiffs partition")
    if ota[:1] != b"\xe9":
        raise Fail("result/luxel-fw-ota.bin does not start with the 0xE9 image magic")

    img = bytearray(stock)
    img[FS_OFFSET : FS_OFFSET + len(fs)] = fs

    if slot == "app1":
        img[APP1 : APP1 + len(ota)] = ota
        # WLED's own otadata (0xE000, seq=1) stays valid and untouched; the
        # higher sequence number in the second entry wins, so the stock
        # bootloader boots app1 — same as if WLED had activated the upload.
        img[WLED_OTADATA_1 : WLED_OTADATA_1 + 32] = otadata_entry(2)
    else:
        img[APP0 : APP0 + len(ota)] = ota
        # otadata untouched: stock seq=1 already selects app0.
    return img


# --------------------------------------------------------------------------
# emulator


def resolve_qemu(explicit: str | None) -> str:
    if explicit:
        cand = explicit
        if os.path.isdir(cand):
            cand = os.path.join(cand, "bin", "qemu-system-xtensa")
        if not os.access(cand, os.X_OK):
            raise Fail(f"--qemu {explicit}: no executable qemu-system-xtensa")
        return cand

    attempts = [
        ["nix", "build", "--no-link", "--print-out-paths", f"{REPO}#qemu-espressif"],
        [
            "nix", "build", "--no-link", "--print-out-paths", "--impure",
            "--expr", f"import {HERE}/qemu-espressif.nix {{}}",
        ],
    ]
    errors = []
    for cmd in attempts:
        p = subprocess.run(cmd, capture_output=True, text=True)
        if p.returncode == 0 and p.stdout.strip():
            out = p.stdout.strip().splitlines()[-1]
            binary = os.path.join(out, "bin", "qemu-system-xtensa")
            if os.access(binary, os.X_OK):
                return binary
            errors.append(f"{out} has no bin/qemu-system-xtensa")
        else:
            errors.append(p.stderr.strip().splitlines()[-1] if p.stderr.strip() else "nix build failed")
    raise Fail("could not resolve qemu-espressif:\n  " + "\n  ".join(errors))


def make_efuse(path: str) -> None:
    p = subprocess.run(
        [sys.executable, os.path.join(HERE, "make-efuse.py"), "-o", path],
        capture_output=True,
        text=True,
    )
    if p.returncode != 0:
        raise Fail(f"make-efuse.py failed:\n{p.stderr}")


def run_qemu(qemu: str, flash: str, efuse: str, log: str, timeout: float) -> tuple[str, float]:
    """Boot the composed image; return (serial log, wall seconds).

    Marker-driven: returns as soon as boot 2 proves credential inheritance.
    NOTE the flash drive deliberately has no `snapshot=on` — the post-run
    assertions diff the file QEMU wrote.
    """
    cmd = [
        qemu, "-display", "none", "-monitor", "none", "-machine", "esp32",
        "-drive", f"file={flash},if=mtd,format=raw",
        "-drive", f"file={efuse},if=none,format=raw,id=efuse,snapshot=on",
        "-global", "driver=nvram.esp32.efuse,property=drive,value=efuse",
        "-serial", f"file:{log}",
    ]
    open(log, "wb").close()
    start = time.monotonic()
    with open(os.devnull, "rb") as devnull:
        proc = subprocess.Popen(cmd, stdin=devnull, stdout=subprocess.DEVNULL,
                                stderr=subprocess.PIPE)
        text = ""
        outcome = None
        try:
            while True:
                with open(log, "rb") as f:
                    text = f.read().decode("utf-8", "replace")
                if KILL_MARKER in text.split(REBOOT_LINE)[-1] and REBOOT_LINE in text:
                    outcome = "marker"
                    break
                for m in ABORT_MARKERS:
                    if m in text:
                        outcome = f"abort line: {m.strip()}"
                        if m in ABORT_HINTS:
                            outcome += f"\n  {ABORT_HINTS[m]}"
                        break
                if outcome:
                    break
                if proc.poll() is not None:
                    outcome = f"qemu exited early (rc={proc.returncode})"
                    break
                if time.monotonic() - start > timeout:
                    outcome = f"timeout after {timeout:.0f}s"
                    break
                time.sleep(0.25)
        finally:
            if proc.poll() is None:
                proc.terminate()
                try:
                    proc.wait(timeout=10)
                except subprocess.TimeoutExpired:
                    proc.kill()
                    proc.wait()
    elapsed = time.monotonic() - start
    with open(log, "rb") as f:
        text = f.read().decode("utf-8", "replace")
    if outcome != "marker":
        stderr = proc.stderr.read().decode("utf-8", "replace") if proc.stderr else ""
        raise Fail(f"boot did not reach the success marker — {outcome}"
                   + (f"\nqemu stderr:\n{stderr.strip()}" if stderr.strip() else ""))
    return text, elapsed


# --------------------------------------------------------------------------
# assertions


class Checks:
    def __init__(self) -> None:
        self.passed: list[str] = []

    def ok(self, what: str) -> None:
        self.passed.append(what)

    def require(self, cond: bool, what: str, detail: str = "") -> None:
        if not cond:
            raise Fail(f"{what}\n  {detail}" if detail else what)
        self.ok(what)

    def line(self, hay: str, needle: str, where: str) -> None:
        self.require(needle in hay, f"serial[{where}]: {needle!r}",
                     f"not found in the {where} section of the log")


def check_serial(log: str, slot: str, ota_len: int, c: Checks) -> None:
    if REBOOT_LINE not in log:
        raise Fail("takeover never reached the table rewrite")
    boot1, boot2 = log.split(REBOOT_LINE, 1)

    c.line(boot1, "takeover: foreign partition table at 0x8000 — installing Luxel layout", "boot1")
    c.line(boot1, f'takeover: inherited WiFi credentials for "{SSID}"', "boot1")
    if slot == "app1":
        c.line(boot1, f"takeover: copying {ota_len} B 0x190000 → 0x10000", "boot1")
        # copy_image() narrates every 64th sector; the last such line is the
        # progress proof that the whole image went through the verify loop.
        sectors = -(-ota_len // SECTOR)
        total_kib = sectors * SECTOR // 1024
        last = ((sectors - 1) // 64) * 64 * SECTOR // 1024
        c.line(boot1, f"takeover: copied {last}/{total_kib} KiB", "boot1")
    else:
        c.line(boot1, "takeover: image already in place at 0x10000", "boot1")
    c.line(boot1, "takeover: wiping config/otadata sectors 0x9000..0x10000", "boot1")
    c.line(boot1, "takeover: WiFi credentials carried over", "boot1")
    c.ok(f"serial[boot1]: {REBOOT_LINE!r}")

    c.line(boot2, "booted from: ota_0", "boot2")
    c.line(boot2, KILL_MARKER, "boot2")


def check_flash(flash: bytes, expected_table: bytes, ota: bytes, fs: bytes,
                slot: str, c: Checks) -> None:
    got = flash[TABLE_OFFSET : TABLE_OFFSET + TABLE_LEN]
    c.require(got == expected_table, "flash: Luxel partition table installed at 0x8000",
              f"first differing byte at {first_diff(got, expected_table)}")

    check_lxcf(flash, c)

    got = flash[APP0 : APP0 + len(ota)]
    c.require(got == ota, f"flash: ota_0 (0x10000) holds the {len(ota)} B app image byte-for-byte",
              f"first differing byte at {first_diff(got, ota)}")

    if slot == "app1":
        # The takeover never writes to its source.  Only the first 0x80000 of
        # WLED's app1 survives the *boot* though: under the freshly installed
        # Luxel table 0x210000 is the `storage` partition, and boot 2's pattern
        # store finds a foreign format there and wipes it ("patterns: format 0
        # != 4, wiping storage").  That reclaim is the new table working as
        # designed, so assert the takeover-owned half and the reclaim
        # separately rather than the whole slot.
        got = flash[APP1:LUXEL_STORAGE]
        want = ota[: LUXEL_STORAGE - APP1]
        c.require(got == want, "flash: copy source 0x190000..0x210000 left untouched",
                  f"first differing byte at {first_diff(got, want)}")
        tail_before = ota[LUXEL_STORAGE - APP1 :]
        tail_after = flash[LUXEL_STORAGE : APP1 + len(ota)]
        c.require(tail_after != tail_before,
                  "flash: 0x210000+ reclaimed as Luxel `storage` (old app1 tail gone)",
                  "the pattern store did not wipe storage — did the new table take effect?")

    got = flash[FS_OFFSET : FS_OFFSET + len(fs)]
    c.require(got == fs, "flash: WLED littlefs at 0x310000 untouched",
              f"first differing byte at {first_diff(got, fs)}")

    # 0xC000 is the boot-guard sector (ota.rs GUARD_OFFSET), inside the wiped
    # range but rewritten by boot 2's `boot_guard()` before the takeover check
    # even runs.  So it is NOT erased: expect the record, attempt count 1.
    guard = flash[LXBG_OFFSET : LXBG_OFFSET + 8]
    c.require(guard[0:4] == b"LXBG" and guard[4] == 1 and guard[5] == 0,
              "flash: boot-guard record at 0xC000 (LXBG, 1 attempt, no force-AP)",
              f"got {guard.hex()}")

    # 0xD000 is Luxel's otadata.  The takeover wipes it, so the next boot's
    # ESP-IDF second-stage bootloader finds both entries erased, falls back to
    # ota_0 — and *writes the choice back* (`set_actual_ota_seq()`: seq =
    # index + 1, ota_state = ESP_OTA_IMG_VALID, CRC over the seq word).  So
    # "erased" is the wrong expectation here; this is the observed and correct
    # post-fallback state.  WLED's bootloader logs at a level that hides the
    # usual "Set actual ota_seq=1" line, hence asserting the bytes.
    ota0 = flash[LUXEL_OTADATA : LUXEL_OTADATA + 32]
    seq, = struct.unpack("<I", ota0[0:4])
    state, crc = struct.unpack("<II", ota0[24:32])
    want_crc = zlib.crc32(ota0[0:4], 0xFFFFFFFF) & 0xFFFFFFFF
    c.require(seq == 1 and state == ESP_OTA_IMG_VALID and crc == want_crc,
              "flash: otadata 0xD000 rewritten by the bootloader as seq=1/VALID (-> ota_0)",
              f"seq={seq} state={state} crc={crc:#010x} want {want_crc:#010x} raw={ota0.hex()}")
    ota1 = flash[LUXEL_OTADATA + SECTOR : LUXEL_OTADATA + SECTOR + 32]
    c.require(ota1 == b"\xff" * 32, "flash: otadata entry #1 (0xE000) still erased",
              f"got {ota1.hex()}")


def check_lxcf(flash: bytes, c: Checks) -> None:
    """The inherited-credentials record written by config::write_wifi()."""
    rec = flash[LXCF_OFFSET : LXCF_OFFSET + SECTOR]
    c.require(rec[0:4] == b"LXCF", "flash: LXCF creds record at 0x9000", f"got {rec[0:8].hex()}")
    ver, slen, plen, pad = rec[4], rec[5], rec[6], rec[7]
    c.require(ver == 1 and pad == 0, "flash: LXCF version 1", f"ver={ver} pad={pad}")
    ssid = rec[8 : 8 + slen].decode("utf-8", "replace")
    c.require(ssid == SSID, f"flash: inherited ssid {SSID!r}", f"got {ssid!r}")
    c.require(plen == PASS_LEN, f"flash: inherited password length {PASS_LEN}", f"got {plen}")
    end = 8 + slen + plen
    stored = struct.unpack("<I", rec[end : end + 4])[0]
    want = sum(rec[:end]) & 0xFFFFFFFF  # config.rs: wrapping u32 byte sum
    c.require(stored == want, "flash: LXCF checksum valid",
              f"stored {stored:#010x} want {want:#010x}")
    tail = rec[end + 4 :]
    c.require(tail == b"\xff" * len(tail), "flash: rest of the 0x9000 sector erased",
              f"first non-0xFF at {first_diff(tail, b'\xff' * len(tail))}")


def first_diff(a: bytes, b: bytes) -> str:
    n = min(len(a), len(b))
    for i in range(n):
        if a[i] != b[i]:
            return f"+{i:#x} ({a[i]:#04x} != {b[i]:#04x})"
    return f"length {len(a)} != {len(b)}"


# --------------------------------------------------------------------------


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--stock", required=True, help="athom-wled-stock.bin (4 MiB full dump)")
    ap.add_argument("--fs", required=True, help="athom-wled-fs-configured.bin (983040 B littlefs)")
    ap.add_argument("--result-dir", default="result",
                    help="nix build .#luxel-fw-athom-music output (default ./result)")
    ap.add_argument("--qemu", help="qemu-system-xtensa (or its store dir); default: nix build")
    ap.add_argument("--slot", choices=("app0", "app1"), default="app1",
                    help="which WLED app slot receives the upload (default app1)")
    ap.add_argument("--workdir", help="where to compose (default: a temp dir)")
    ap.add_argument("--keep", action="store_true", help="keep the work dir on success")
    ap.add_argument("--timeout", type=float, default=300.0,
                    help="overall boot timeout in seconds (default 300)")
    args = ap.parse_args(argv)

    workdir = args.workdir or tempfile.mkdtemp(prefix="luxel-takeover-")
    os.makedirs(workdir, exist_ok=True)
    log = os.path.join(workdir, "serial.log")
    try:
        rc = run(args, workdir, log)
    except Fail as e:
        print(f"\nFAIL [{args.slot}]: {e}", file=sys.stderr)
        if os.path.exists(log):
            with open(log, "rb") as f:
                tail = f.read().decode("utf-8", "replace").splitlines()[-40:]
            print("\n--- serial tail ---", file=sys.stderr)
            print("\n".join(tail), file=sys.stderr)
        print(f"\nwork dir kept: {workdir}", file=sys.stderr)
        return 1
    if args.keep or args.workdir:
        print(f"work dir: {workdir}")
    else:
        shutil.rmtree(workdir, ignore_errors=True)
    return rc


def run(args: argparse.Namespace, workdir: str, log: str) -> int:
    ota_path = os.path.join(args.result_dir, "luxel-fw-ota.bin")
    merged_path = os.path.join(args.result_dir, "luxel-fw.bin")
    for p in (args.stock, args.fs, ota_path, merged_path):
        if not os.path.exists(p):
            built = p in (ota_path, merged_path)
            raise Fail(f"missing input: {p}"
                       + ("\n  run: nix build .#luxel-fw-athom-music" if built else ""))

    stock = open(args.stock, "rb").read()
    fs = open(args.fs, "rb").read()
    ota = open(ota_path, "rb").read()
    # Same build for both: the takeover matches the 256-byte esp_app_desc
    # (build timestamp included) at slot+0x20 against the running image.
    expected_table = open(merged_path, "rb").read()[TABLE_OFFSET : TABLE_OFFSET + TABLE_LEN]

    print(f"== WLED takeover test, --slot {args.slot} ==")
    print(f"   app image : {ota_path} ({len(ota)} B)")
    print(f"   work dir  : {workdir}")

    img = compose(stock, fs, ota, args.slot)
    flash = os.path.join(workdir, "flash.bin")
    with open(flash, "wb") as f:
        f.write(img)
    efuse = os.path.join(workdir, "efuse.bin")
    make_efuse(efuse)

    qemu = resolve_qemu(args.qemu)
    print(f"   qemu      : {qemu}")
    print("   booting…")
    text, elapsed = run_qemu(qemu, flash, efuse, log, args.timeout)
    print(f"   reached the inheritance marker in {elapsed:.1f}s wall")

    c = Checks()
    check_serial(text, args.slot, len(ota), c)
    with open(flash, "rb") as f:
        written = f.read()
    check_flash(written, expected_table, ota, fs, args.slot, c)

    print(f"\nPASS [{args.slot}] — {len(c.passed)} assertions in {elapsed:.1f}s")
    for a in c.passed:
        print(f"  ok  {a}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
