//! WLED → Luxel self-install ("takeover"). Always built in: on a device
//! already running the Luxel layout it costs one 256-byte flash read per
//! boot, and having it everywhere means any future partitions.csv change
//! ships to installed devices as an ordinary OTA (the image notices the
//! old table on first boot and migrates itself).
//!
//! A Luxel app image uploaded through WLED's own OTA updater lands in one
//! of WLED's two 1.5 MB app slots and boots under WLED's partition table —
//! ESP32 app images are position-independent across slots (the bootloader
//! MMU-maps whichever slot otadata points at), and WLED's updater accepts
//! any image with the 0xE9 magic. On boot this module notices the foreign
//! table, copies the running image into what will become ota_0 (0x10000 —
//! app0 has the same offset in both layouts), wipes the config/otadata
//! sectors, rewrites the partition table to Luxel's, and reboots. The
//! second-stage bootloader (WLED's own — never touched) reads the new
//! table, finds otadata erased, and falls back to ota_0: Luxel. The next
//! boot sees a matching table and this module does nothing.
//!
//! Crash-safety: every step before the final table rewrite leaves WLED's
//! table and otadata intact, so a power cut mid-copy just re-runs the
//! takeover on the next boot. The only serial-recovery-only window is the
//! single 4 KiB erase+write of the table sector itself (milliseconds).
//! If a takeover build crash-loops before getting this far, ota::boot_guard
//! (which runs first) flips otadata back to the WLED slot on the third
//! failed boot — the device recovers to stock WLED on its own.
//!
//! Settings inheritance: before touching anything, the takeover mounts
//! WLED's littlefs (read-only, src/wledfs.rs) and lifts the WiFi
//! credentials out of cfg.json/wsec.json; after the config wipe they are
//! written into Luxel's own creds record, so the device reappears on the
//! same network without ever being provisioned. A factory-fresh WLED (or
//! any parse failure) inherits nothing and Luxel boots its provisioning
//! AP instead — the fallback path, not an error.

use alloc::vec::Vec;
use embedded_storage::nor_flash::NorFlash;
use esp_println::println;

/// Luxel's partition table binary (entries + trailing MD5 row, which the
/// bootloader verifies), generated by build.rs from partitions.csv — the
/// exact bytes espflash would flash at 0x8000.
const LUXEL_TABLE: &[u8] = include_bytes!(concat!(env!("OUT_DIR"), "/partition-table.bin"));

const TABLE_OFFSET: u32 = 0x8000;
const SECTOR: u32 = 4096;
/// nvs + boot-guard + otadata (+ phy_init) sectors under BOTH layouts:
/// wiped so Luxel starts from config defaults and the bootloader's
/// empty-otadata fallback picks ota_0.
const CONFIG_WIPE: core::ops::Range<u32> = 0x9000..0x10000;

const ENTRY_MAGIC: [u8; 2] = [0xAA, 0x50];
const TYPE_APP: u8 = 0x00;
const TYPE_DATA: u8 = 0x01;
const SUBTYPE_OTA0: u8 = 0x10;
/// data/spiffs — what WLED's table calls its littlefs partition
const SUBTYPE_SPIFFS: u8 = 0x82;

#[derive(Clone, Copy)]
struct Part {
    ptype: u8,
    subtype: u8,
    offset: u32,
    len: u32,
}

/// All entries of a raw partition table.
fn entries(table: &[u8]) -> Vec<Part> {
    let mut out = Vec::new();
    for e in table.chunks_exact(32) {
        if e[0..2] != ENTRY_MAGIC {
            break; // MD5 row (0xEBEB) or erased flash
        }
        out.push(Part {
            ptype: e[2],
            subtype: e[3],
            offset: u32::from_le_bytes(e[4..8].try_into().unwrap()),
            len: u32::from_le_bytes(e[8..12].try_into().unwrap()),
        });
    }
    out
}

fn app_entries(table: &[u8]) -> Vec<Part> {
    let mut v = entries(table);
    v.retain(|p| p.ptype == TYPE_APP);
    v
}

/// Best-effort WiFi inheritance from the outgoing firmware's filesystem
/// (WLED: littlefs in its `spiffs` data partition). Read-only; any
/// failure just returns None and the provisioning AP covers it.
fn inherit_wifi(live_table: &[u8]) -> Option<(alloc::string::String, alloc::string::String)> {
    let fs_part = entries(live_table)
        .into_iter()
        .find(|p| p.ptype == TYPE_DATA && p.subtype == SUBTYPE_SPIFFS)?;
    let base = fs_part.offset;
    let mut read = |off: u32, buf: &mut [u8]| {
        off.checked_add(base)
            .is_some_and(|abs| crate::assets::read_chunk(abs, buf))
    };
    crate::wledfs::extract_wifi(&mut read, fs_part.len)
}

/// This build's app descriptor as raw bytes. Every app image carries it at
/// image offset 0x20 (right behind the 24-byte image header + first
/// 8-byte segment header). Version + project name + toolchain build stamp
/// distinguish it from any foreign firmware (which is all this needs:
/// the descriptor only locates *a* Luxel image under a foreign table) —
/// comparing against flash finds our slot without trusting otadata.
fn own_desc_bytes() -> &'static [u8] {
    let d: &'static esp_bootloader_esp_idf::EspAppDesc = &crate::ESP_APP_DESC;
    unsafe {
        core::slice::from_raw_parts(
            (d as *const esp_bootloader_esp_idf::EspAppDesc).cast::<u8>(),
            core::mem::size_of::<esp_bootloader_esp_idf::EspAppDesc>(),
        )
    }
}

/// Total byte length of the app image at `base`, by walking its segment
/// table (header: 0xE9, segment count, …, entry point; then per segment an
/// 8-byte load-addr/size header). The image ends with a checksum byte
/// padded to 16, plus an appended SHA-256 when header byte 23 says so.
fn image_len(base: u32) -> Option<u32> {
    let mut hdr = [0u8; 24];
    if !crate::assets::read_chunk(base, &mut hdr) || hdr[0] != 0xE9 {
        return None;
    }
    let segments = hdr[1];
    if segments == 0 || segments > 16 {
        return None;
    }
    let hash_appended = hdr[23] == 1;
    let mut pos: u32 = 24;
    for _ in 0..segments {
        let mut seg = [0u8; 8];
        if !crate::assets::read_chunk(base + pos, &mut seg) {
            return None;
        }
        let size = u32::from_le_bytes(seg[4..8].try_into().unwrap());
        if size > 4 * 1024 * 1024 {
            return None;
        }
        pos += 8 + size;
    }
    pos = (pos + 1 + 15) & !15; // checksum byte, padded to 16
    if hash_appended {
        pos += 32;
    }
    Some(pos)
}

fn erase_sector(at: u32) -> bool {
    crate::ota::with_flash(|f| NorFlash::erase(f, at, at + SECTOR).is_ok()).unwrap_or(false)
}

/// Write `bytes` (word-multiple length) at `at`, staged through a
/// word-aligned heap buffer (see config.rs: unaligned paths are off
/// limits). The sector must already be erased.
fn write_aligned(at: u32, bytes: &[u8]) -> bool {
    let mut stage = alloc::vec![0u32; bytes.len().div_ceil(4)];
    let stage_bytes = unsafe {
        core::slice::from_raw_parts_mut(stage.as_mut_ptr().cast::<u8>(), stage.len() * 4)
    };
    stage_bytes[..bytes.len()].copy_from_slice(bytes);
    stage_bytes[bytes.len()..].fill(0xFF);
    crate::ota::with_flash(|f| NorFlash::write(f, at, stage_bytes).is_ok()).unwrap_or(false)
}

/// Copy `len` bytes from `src` to `dst` sector by sector with read-back
/// verification. Runs pre-WiFi on the main task; buffers live on the heap.
fn copy_image(src: u32, dst: u32, len: u32) -> bool {
    let sectors = len.div_ceil(SECTOR);
    let mut buf = alloc::vec![0u8; SECTOR as usize];
    let mut check = alloc::vec![0u8; SECTOR as usize];
    for s in 0..sectors {
        let off = s * SECTOR;
        if !crate::assets::read_chunk(src + off, &mut buf) {
            println!("takeover: read failed at {:#x}", src + off);
            return false;
        }
        // one retry per sector: the write path has no other error recovery
        let mut ok = false;
        for _attempt in 0..2 {
            if erase_sector(dst + off)
                && write_aligned(dst + off, &buf)
                && crate::assets::read_chunk(dst + off, &mut check)
                && check == buf
            {
                ok = true;
                break;
            }
        }
        if !ok {
            println!("takeover: verify failed at {:#x}", dst + off);
            return false;
        }
        if s % 64 == 0 {
            println!("takeover: copied {}/{} KiB", off / 1024, sectors * SECTOR / 1024);
        }
    }
    true
}

/// Called once at boot, after ota::init + ota::boot_guard and before any
/// module that touches data partitions. No-op (one 256-byte flash read)
/// when the partition table is already Luxel's.
pub fn maybe_takeover() {
    let mut live = alloc::vec![0u8; LUXEL_TABLE.len()];
    if !crate::assets::read_chunk(TABLE_OFFSET, &mut live) {
        return;
    }
    if live == LUXEL_TABLE {
        return;
    }
    println!("takeover: foreign partition table at {:#x} — installing Luxel layout", TABLE_OFFSET);

    // Flash-size preflight: never write a table that references flash the
    // chip doesn't have (a 2 MB part would brick on the first boot after).
    let needed = entries(LUXEL_TABLE)
        .iter()
        .map(|p| p.offset.saturating_add(p.len))
        .max()
        .unwrap_or(0);
    let cap = crate::ota::with_flash(|f| f.capacity() as u32).unwrap_or(0);
    if cap < needed {
        println!(
            "takeover: flash too small ({} B < {} B needed) — refusing to repartition",
            cap, needed
        );
        return;
    }

    let Some(dest) = app_entries(LUXEL_TABLE)
        .into_iter()
        .find(|a| a.subtype == SUBTYPE_OTA0)
    else {
        println!("takeover: no ota_0 in embedded table?! aborting");
        return;
    };

    // Inherit the outgoing firmware's WiFi credentials before anything is
    // modified; they are persisted after the config wipe below.
    let inherited = inherit_wifi(&live);
    match &inherited {
        Some((ssid, _)) => println!("takeover: inherited WiFi credentials for \"{}\"", ssid),
        None => println!("takeover: no WiFi credentials to inherit (provisioning AP will cover)"),
    }

    // Candidate slots under the live (foreign) table. Destination offset
    // first: if a previous, interrupted takeover already copied the image
    // there — or WLED happened to write the upload into app0 — skip the
    // copy entirely and never risk touching the region we run from.
    let mut cands = app_entries(&live);
    cands.sort_unstable_by_key(|a| if a.offset == dest.offset { 0u8 } else { 1 });
    let me = own_desc_bytes();
    let mut desc = alloc::vec![0u8; me.len()];
    let src = cands.iter().find(|c| {
        crate::assets::read_chunk(c.offset + 0x20, &mut desc) && desc == me
    });
    let Some(src) = src else {
        println!("takeover: own image not found in any app slot — aborting (still bootable)");
        return;
    };

    if src.offset == dest.offset {
        println!("takeover: image already in place at {:#x}", dest.offset);
    } else {
        let Some(len) = image_len(src.offset) else {
            println!("takeover: cannot size own image — aborting");
            return;
        };
        if len > dest.len {
            println!("takeover: image ({} B) exceeds ota_0 ({} B) — aborting", len, dest.len);
            return;
        }
        // Overlap guard: erasing the destination must never touch the
        // region we are executing from. Can't happen with today's layouts
        // (both put app0 at 0x10000, our slots above it) — this protects
        // future table changes that resize/move app slots.
        if src.offset < dest.offset + dest.len && dest.offset < src.offset + len {
            println!(
                "takeover: running image {:#x}+{} overlaps destination {:#x}+{} — refusing",
                src.offset, len, dest.offset, dest.len
            );
            return;
        }
        println!("takeover: copying {} B {:#x} → {:#x}", len, src.offset, dest.offset);
        if !copy_image(src.offset, dest.offset, len) {
            println!("takeover: copy failed — aborting before table rewrite (WLED table intact)");
            return;
        }
    }

    println!("takeover: wiping config/otadata sectors {:#x}..{:#x}", CONFIG_WIPE.start, CONFIG_WIPE.end);
    let mut at = CONFIG_WIPE.start;
    while at < CONFIG_WIPE.end {
        if !erase_sector(at) {
            println!("takeover: config wipe failed at {:#x} — aborting", at);
            return;
        }
        at += SECTOR;
    }

    // Persist inherited credentials into Luxel's own record (after the
    // wipe, so it survives). Failure is non-fatal: the AP path remains.
    if let Some((ssid, pass)) = inherited {
        match crate::config::write_wifi(&ssid, &pass) {
            Ok(()) => println!("takeover: WiFi credentials carried over"),
            Err(e) => println!("takeover: creds carry-over failed ({}) — AP fallback", e),
        }
    }

    // The point of no return: one sector erase + write. Everything above
    // is re-runnable under the old table; after this line the new table is
    // authoritative and the bootloader boots ota_0.
    if !erase_sector(TABLE_OFFSET) || !write_aligned(TABLE_OFFSET, LUXEL_TABLE) {
        println!("takeover: TABLE WRITE FAILED — device needs a serial reflash");
        return;
    }
    println!("takeover: partition table installed — rebooting into Luxel");
    esp_hal::system::software_reset()
}
