import puppeteer from 'puppeteer-core';
const PORT = 4197, DEV = 'http://192.168.0.238';
const b = await puppeteer.launch({executablePath: process.env.CHROME, headless: true, args:['--no-sandbox']});
const p = await b.newPage(); await p.setViewport({width:1400,height:900});
const errs=[]; p.on('pageerror',e=>errs.push(String(e)));
await p.goto(`http://localhost:${PORT}/?device=${DEV}`, {waitUntil:'domcontentloaded', timeout:60000});
await p.waitForSelector('[data-role="layout-kind"]', {timeout: 90000});
await new Promise(r=>setTimeout(r,4000));
const mapBefore = await (await fetch(DEV+'/api/map')).text();
await p.select('[data-role="layout-kind"]', 'grid');
await p.waitForSelector('[data-role="layout-w"]', {timeout: 10000});
const setNum = async (role, v) => { const el = await p.$(`[data-role="${role}"]`); await el.click({clickCount:3}); await el.type(String(v)); await el.evaluate(e=>e.dispatchEvent(new Event('change'))); };
await setNum('layout-w', 64); await setNum('layout-h', 32);
await p.waitForSelector('[data-role="grid-install"]', {timeout: 10000});
await p.click('[data-role="grid-install"]');
await new Promise(r=>setTimeout(r,3000));
const mapAfter = await (await fetch(DEV+'/api/map')).text();
const badge = await p.$eval('[data-role="map-installed"]', e=>e.textContent.trim()).catch(()=>null);
await p.screenshot({path: process.argv[2]});
await setNum('layout-h', 64); await p.click('[data-role="grid-install"]'); await new Promise(r=>setTimeout(r,3000));
const mapRestored = await (await fetch(DEV+'/api/map')).text();
console.log('before  ', mapBefore); console.log('after   ', mapAfter); console.log('badge   ', badge); console.log('restored', mapRestored); console.log('errors', errs.length? errs: 'none');
await b.close();
