<script lang="ts">
  // Pattern browser: every tile is the real pattern running live on the
  // wasm engine as a small looping thumbnail. The tile's shape follows the
  // pattern's declared layout — a 1D pattern previews as a horizontal bar,
  // a render2D pattern as a rectangle (its mapped grid). Corpus patterns
  // stream in from gallery.json (generated by tools/gen-gallery.mjs);
  // built-in examples always lead.
  //
  // Budgeting: only visible tiles animate (IntersectionObserver), a shared
  // rAF steps at most STEP_BUDGET engines per frame at ~11 fps each, and
  // engines for tiles long out of view are freed beyond a cap — so 190
  // tiles cost no more than a couple dozen small engines.
  import { createEventDispatcher, onDestroy, onMount } from "svelte";
  import { EXAMPLES } from "../lib/examples";
  import { Engine, Luxel } from "../lib/luxel";

  export let luxel: Luxel;

  interface GalleryPick {
    name: string;
    kind: "strip" | "grid";
    source: string;
  }

  interface Tile {
    name: string;
    kind: "strip" | "grid";
    source: string;
    engine?: Engine;
    canvas?: HTMLCanvasElement;
    dead: boolean;
    ready: boolean; // has drawn at least one frame (spinner off)
    last: number; // last stepped (ms)
    seen: number; // last visible (ms)
    visible: boolean;
  }

  const dispatch = createEventDispatcher<{ pick: GalleryPick; close: void }>();

  const STRIP_PX = 64;
  const GRID = 16;
  const STEP_BUDGET = 6; // engine frames per rAF tick
  const TILE_FPS_MS = 90; // ~11 fps per tile
  const ENGINE_CAP = 40;

  let tiles: Tile[] = [];
  let corpusNote = "";
  let loading = true; // corpus (gallery.json) still streaming in
  let raf = 0;
  let cursor = 0;

  const io = new IntersectionObserver((entries) => {
    for (const e of entries) {
      const t = tiles[Number((e.target as HTMLElement).dataset.tile)];
      if (!t) continue;
      t.visible = e.isIntersecting;
      if (t.visible) t.seen = performance.now();
    }
    tiles = tiles; // reflect visibility so spinners only run for in-view tiles
  });

  function register(node: HTMLElement, i: number): { destroy: () => void } {
    node.dataset.tile = String(i);
    const t = tiles[i];
    if (t) t.canvas = node.querySelector("canvas") ?? undefined;
    io.observe(node);
    return { destroy: () => io.unobserve(node) };
  }

  function ensureEngine(t: Tile): void {
    if (t.engine || t.dead) return;
    const px = t.kind === "grid" ? GRID * GRID : STRIP_PX;
    const r = luxel.compile(t.source, px);
    if (r instanceof Engine) {
      if (t.kind === "grid") r.setMapGrid(GRID, GRID);
      r.setWallClock(Date.now() / 1000);
      t.engine = r;
    } else {
      t.dead = true;
      tiles = tiles; // reflect the grayed-out state
    }
  }

  function draw(t: Tile, px: Uint8Array): void {
    const c = t.canvas;
    const ctx = c?.getContext("2d");
    if (!c || !ctx) return;
    if (t.kind === "grid") {
      const cell = c.width / GRID;
      for (let y = 0; y < GRID; y++) {
        for (let x = 0; x < GRID; x++) {
          const i = (y * GRID + x) * 3;
          ctx.fillStyle = `rgb(${px[i]},${px[i + 1]},${px[i + 2]})`;
          ctx.fillRect(x * cell, y * cell, cell + 1, cell + 1);
        }
      }
    } else {
      const w = c.width / STRIP_PX;
      for (let x = 0; x < STRIP_PX; x++) {
        const i = x * 3;
        ctx.fillStyle = `rgb(${px[i]},${px[i + 1]},${px[i + 2]})`;
        ctx.fillRect(x * w, 0, w + 1, c.height);
      }
    }
  }

  function loop(now: number): void {
    raf = requestAnimationFrame(loop);
    if (tiles.length === 0) return;
    let steps = 0;
    let compiles = 0;
    for (let k = 0; k < tiles.length && steps < STEP_BUDGET; k++) {
      cursor = (cursor + 1) % tiles.length;
      const t = tiles[cursor];
      if (!t || !t.visible || t.dead) continue;
      if (!t.engine) {
        // compiling is the expensive part — spread it across frames
        if (compiles >= 2) continue;
        compiles++;
        ensureEngine(t);
        if (!t.engine) continue;
      }
      if (now - t.last < TILE_FPS_MS) continue;
      const dt = t.last === 0 ? 16 : Math.min(now - t.last, 100);
      t.last = now;
      draw(t, t.engine.frame(dt));
      t.engine.takeError(); // tolerate runtime errors; many patterns recover
      if (!t.ready) {
        t.ready = true;
        tiles = tiles; // first frame drawn → drop the spinner
      }
      steps++;
    }
    const live = tiles.filter((t) => t.engine);
    if (live.length > ENGINE_CAP) {
      live.sort((a, b) => a.seen - b.seen);
      for (const t of live.slice(0, live.length - ENGINE_CAP)) {
        if (!t.visible) {
          t.engine?.free();
          t.engine = undefined;
        }
      }
    }
  }

  onMount(async () => {
    const ex: Tile[] = EXAMPLES.map((e) => ({
      name: e.name,
      kind: e.layout.kind === "grid" ? ("grid" as const) : ("strip" as const),
      source: e.source,
      dead: false,
      ready: false,
      last: 0,
      seen: 0,
      visible: false,
    }));
    // show the built-in examples (and start animating) immediately — the
    // corpus fetch below can take a beat, and a blank "0 patterns" while it
    // loads reads as broken
    tiles = ex;
    raf = requestAnimationFrame(loop);
    let corpus: Tile[] = [];
    try {
      const r = await fetch(`${import.meta.env.BASE_URL}gallery.json`);
      if (r.ok) {
        const list = (await r.json()) as { name: string; kind: string; source: string }[];
        const known = new Set(ex.map((t) => t.name.toLowerCase()));
        corpus = list
          .filter((p) => !known.has(p.name.toLowerCase()))
          .map((p) => ({
            name: p.name,
            kind: p.kind === "grid" ? ("grid" as const) : ("strip" as const),
            source: p.source,
            dead: false,
            ready: false,
            last: 0,
            seen: 0,
            visible: false,
          }));
      }
    } catch {
      /* gallery.json is optional — examples still show */
    }
    if (corpus.length === 0) corpusNote = "community patterns unavailable (no gallery.json)";
    tiles = [...ex, ...corpus]; // reuses ex refs, so example engines survive
    loading = false;
  });

  onDestroy(() => {
    cancelAnimationFrame(raf);
    io.disconnect();
    for (const t of tiles) t.engine?.free();
  });
</script>

<div class="browser" role="region" aria-label="pattern browser">
  <header>
    {#if loading}
      <span class="spinner header-spinner" aria-hidden="true"></span>
      <span class="dim" data-role="gallery-loading">loading patterns…</span>
    {:else}
      <span class="dim">{tiles.length} patterns — click one to open it in the editor</span>
    {/if}
    {#if corpusNote}<span class="dim">· {corpusNote}</span>{/if}
  </header>
  <div class="tiles">
    {#each tiles as t, i (i)}
      <button
        class="tile"
        class:dead={t.dead}
        data-kind={t.kind}
        title={t.dead ? `${t.name} (does not compile)` : t.name}
        use:register={i}
        on:click={() => !t.dead && dispatch("pick", { name: t.name, kind: t.kind, source: t.source })}
      >
        <span class="thumb" class:strip={t.kind !== "grid"}>
          {#if t.kind === "grid"}
            <canvas width="96" height="96"></canvas>
          {:else}
            <canvas width="128" height="18"></canvas>
          {/if}
          {#if t.visible && !t.ready && !t.dead}
            <span class="spinner" aria-label="loading" title="computing preview…"></span>
          {/if}
        </span>
        <span class="tname">{t.name}</span>
      </button>
    {/each}
  </div>
</div>

<style>
  .browser {
    height: 100%;
    background: var(--bg, #14161a);
    display: flex;
    flex-direction: column;
  }

  header {
    display: flex;
    align-items: center;
    gap: 10px;
    padding: 8px 14px;
    border-bottom: 1px solid var(--border);
    background: var(--bg-panel);
    font-size: 13px;
  }

  .dim {
    color: var(--text-dim);
  }

  .tiles {
    flex: 1;
    overflow-y: auto;
    display: grid;
    grid-template-columns: repeat(auto-fill, minmax(150px, 1fr));
    gap: 10px;
    padding: 12px;
    align-content: start;
  }

  .tile {
    display: flex;
    flex-direction: column;
    align-items: center;
    gap: 6px;
    padding: 8px 6px;
    border: 1px solid var(--border);
    border-radius: 8px;
    background: var(--bg-inset);
    cursor: pointer;
  }

  .tile:hover {
    border-color: var(--accent);
  }

  .tile.dead {
    opacity: 0.35;
    cursor: default;
  }

  .thumb {
    position: relative;
    display: inline-flex;
    max-width: 100%;
  }

  .thumb.strip {
    width: 100%;
    justify-content: center;
  }

  .tile canvas {
    image-rendering: pixelated;
    border-radius: 3px;
    background: #000;
    max-width: 100%;
  }

  .spinner {
    position: absolute;
    top: 50%;
    left: 50%;
    width: 14px;
    height: 14px;
    margin: -7px 0 0 -7px;
    border: 2px solid color-mix(in srgb, var(--text-dim) 40%, transparent);
    border-top-color: var(--accent);
    border-radius: 50%;
    animation: tile-spin 0.7s linear infinite;
  }

  .header-spinner {
    position: static;
    display: inline-block;
    margin: 0;
    vertical-align: middle;
  }

  @keyframes tile-spin {
    to {
      transform: rotate(1turn);
    }
  }

  .tname {
    font-size: 11px;
    color: var(--text-dim);
    max-width: 100%;
    overflow: hidden;
    text-overflow: ellipsis;
    white-space: nowrap;
  }
</style>
